// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::id_token::IdTokenType;
use crate::v2_1::datatypes::id_token_info::IdTokenInfoType;
use crate::v2_1::datatypes::ocsp_request_data::OCSPRequestDataType;
use crate::v2_1::datatypes::tariff::TariffType;
use crate::v2_1::enumerations::authorize_certificate_status::AuthorizeCertificateStatusEnumType;
use crate::v2_1::enumerations::energy_transfer_mode::EnergyTransferModeEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct AuthorizeRequest {
    /// *(2.1)* The X.509 certificate chain presented by EV and encoded in PEM format. Order of certificates in chain is from leaf up to (but excluding) root certificate. +
    /// Only needed in case of central contract validation when Charging Station cannot validate the contract certificate.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 10000))]
    pub certificate: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub id_token: IdTokenType,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 4))]
    pub iso_15118_certificate_hash_data: Option<Vec<OCSPRequestDataType>>,
}

static_assertions::assert_impl_all!(AuthorizeRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct AuthorizeResponse {
    /// *(2.1)* List of allowed energy transfer modes the EV can choose from. If omitted this defaults to charging only.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub allowed_energy_transfer: Option<Vec<EnergyTransferModeEnumType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certificate_status: Option<AuthorizeCertificateStatusEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub id_token_info: IdTokenInfoType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tariff: Option<TariffType>,
}

static_assertions::assert_impl_all!(AuthorizeResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
