// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::battery_data::BatteryDataType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::id_token::IdTokenType;
use crate::v2_1::enumerations::battery_swap_event::BatterySwapEventEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct BatterySwapRequest {
    #[validate(length(min = 1))]
    pub battery_data: Vec<BatteryDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub event_type: BatterySwapEventEnumType,
    pub id_token: IdTokenType,
    /// RequestId to correlate BatteryIn/Out events and optional RequestBatterySwapRequest.
    pub request_id: i32,
}

static_assertions::assert_impl_all!(BatterySwapRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

/// This is an empty response that just acknowledges receipt of the request. (The request cannot be rejected).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct BatterySwapResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(BatterySwapResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
