// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::clear_tariffs_result::ClearTariffsResultType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ClearTariffsRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// When present only clear tariffs matching _tariffIds_ at EVSE _evseId_.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub evse_id: Option<u32>,
    /// List of tariff Ids to clear. When absent clears all tariffs at _evseId_.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub tariff_ids: Option<Vec<String>>,
}

static_assertions::assert_impl_all!(ClearTariffsRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ClearTariffsResponse {
    #[validate(length(min = 1))]
    pub clear_tariffs_result: Vec<ClearTariffsResultType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(ClearTariffsResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
