// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::clear_monitoring_result::ClearMonitoringResultType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ClearVariableMonitoringRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// List of the monitors to be cleared, identified by there Id.
    #[validate(length(min = 1))]
    pub id: Vec<u32>,
}

static_assertions::assert_impl_all!(ClearVariableMonitoringRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ClearVariableMonitoringResponse {
    #[validate(length(min = 1))]
    pub clear_monitoring_result: Vec<ClearMonitoringResultType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(ClearVariableMonitoringResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
