// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::certificate_hash_data::CertificateHashDataType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::id_token::IdTokenType;
use crate::v2_1::datatypes::status_info::StatusInfoType;
use crate::v2_1::enumerations::customer_information_status::CustomerInformationStatusEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct CustomerInformationRequest {
    /// Flag indicating whether the Charging Station should clear all information about the customer referred to.
    pub clear: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_certificate: Option<CertificateHashDataType>,
    /// A (e.g. vendor specific) identifier of the customer this request refers to. This field contains a custom identifier other than IdToken and Certificate.
    /// One of the possible identifiers (customerIdentifier, customerIdToken or customerCertificate) should be in the request message.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 64))]
    pub customer_identifier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_token: Option<IdTokenType>,
    /// Flag indicating whether the Charging Station should return NotifyCustomerInformationRequest messages containing information about the customer referred to.
    pub report: bool,
    /// The Id of the request.
    #[validate(range(min = 0))]
    pub request_id: u32,
}

static_assertions::assert_impl_all!(CustomerInformationRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct CustomerInformationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: CustomerInformationStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(CustomerInformationResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
