// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::certificate_status::CertificateStatusType;
use crate::v2_1::datatypes::certificate_status_request_info::CertificateStatusRequestInfoType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct GetCertificateChainStatusRequest {
    #[validate(length(min = 1, max = 4))]
    pub certificate_status_requests: Vec<CertificateStatusRequestInfoType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(GetCertificateChainStatusRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct GetCertificateChainStatusResponse {
    #[validate(length(min = 1, max = 4))]
    pub certificate_status: Vec<CertificateStatusType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(GetCertificateChainStatusResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
