// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::status_info::StatusInfoType;
use crate::v2_1::enumerations::certificate_action::CertificateActionEnumType;
use crate::v2_1::enumerations::iso15118ev_certificate_status::Iso15118EVCertificateStatusEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct Get15118EVCertificateRequest {
    pub action: CertificateActionEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// *(2.1)* Raw CertificateInstallationReq request from EV, Base64 encoded. +
    /// Extended to support ISO 15118-20 certificates. The minimum supported length is 11000. If a longer _exiRequest_ is supported, then the supported length must be communicated in variable OCPPCommCtrlr.FieldLength[ "Get15118EVCertificateRequest.exiRequest" ].
    #[validate(length(max = 11000))]
    pub exi_request: String,
    /// Schema version currently used for the 15118 session between EV and Charging Station. Needed for parsing of the EXI stream by the CSMS.
    #[validate(length(max = 50))]
    pub iso_15118_schema_version: String,
    /// *(2.1)* Absent during ISO 15118-2 session. Required during ISO 15118-20 session. +
    /// Maximum number of contracts that EV wants to install.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub maximum_contract_certificate_chains: Option<u32>,
    /// *(2.1)*  Absent during ISO 15118-2 session. Optional during ISO 15118-20 session. List of EMAIDs for which contract certificates must be requested first, in case there are more certificates than allowed by _maximumContractCertificateChains_.
    #[serde(rename = "prioritizedEMAIDs")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 8))]
    pub prioritized_emai_ds: Option<Vec<String>>,
}

static_assertions::assert_impl_all!(Get15118EVCertificateRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct Get15118EVCertificateResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// *(2/1)* Raw CertificateInstallationRes response for the EV, Base64 encoded. +
    /// Extended to support ISO 15118-20 certificates. The minimum supported length is 17000. If a longer _exiResponse_ is supported, then the supported length must be communicated in variable OCPPCommCtrlr.FieldLength[ "Get15118EVCertificateResponse.exiResponse" ].
    #[validate(length(max = 17000))]
    pub exi_response: String,
    /// *(2.1)* Number of contracts that can be retrieved with additional requests.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub remaining_contracts: Option<u32>,
    pub status: Iso15118EVCertificateStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(Get15118EVCertificateResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
