// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::der_control::DERControlEnumType;
use crate::v2_1::enumerations::grid_event_fault::GridEventFaultEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyDERAlarmRequest {
    /// True when error condition has ended.
    /// Absent or false when alarm has started.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alarm_ended: Option<bool>,
    pub control_type: DERControlEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Optional info provided by EV.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 200))]
    pub extra_info: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grid_event_fault: Option<GridEventFaultEnumType>,
    /// Time of start or end of alarm.
    #[serde(with = "datetime_rfc3339")]
    pub timestamp: DateTime<Utc>,
}

static_assertions::assert_impl_all!(NotifyDERAlarmRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyDERAlarmResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(NotifyDERAlarmResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
