// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::address::AddressType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::payment_status::PaymentStatusEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifySettlementRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The payment reference received from the payment terminal and is used as the value for _idToken_.
    #[validate(length(max = 255))]
    pub psp_ref: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub receipt_id: Option<String>,
    /// The receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 2000))]
    pub receipt_url: Option<String>,
    /// The amount that was settled, or attempted to be settled (in case of failure).
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub settlement_amount: Decimal,
    /// The time when the settlement was done.
    #[serde(with = "datetime_rfc3339")]
    pub settlement_time: DateTime<Utc>,
    pub status: PaymentStatusEnumType,
    /// Additional information from payment terminal/payment process.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 500))]
    pub status_info: Option<String>,
    /// The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 36))]
    pub transaction_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vat_company: Option<AddressType>,
    /// VAT number for a company receipt.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 20))]
    pub vat_number: Option<String>,
}

static_assertions::assert_impl_all!(NotifySettlementRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifySettlementResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The receipt id if the receipt is generated by CSMS.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub receipt_id: Option<String>,
    /// The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 2000))]
    pub receipt_url: Option<String>,
}

static_assertions::assert_impl_all!(NotifySettlementResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
