// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyDERStartStopRequest {
    /// Id of the started or stopped DER control.
    /// Corresponds to the _controlId_ of the SetDERControlRequest.
    #[validate(length(max = 36))]
    pub control_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// True if DER control has started. False if it has ended.
    pub started: bool,
    /// List of controlIds that are superseded as a result of this control starting.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub superseded_ids: Option<Vec<String>>,
    /// Time of start or end of event.
    #[serde(with = "datetime_rfc3339")]
    pub timestamp: DateTime<Utc>,
}

static_assertions::assert_impl_all!(NotifyDERStartStopRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyDERStartStopResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(NotifyDERStartStopResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
