// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::charging_schedule::ChargingScheduleType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::status_info::StatusInfoType;
use crate::v2_1::enumerations::generic_status::GenericStatusEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyEVChargingScheduleRequest {
    pub charging_schedule: ChargingScheduleType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The charging schedule contained in this notification applies to an EVSE. EvseId must be &gt; 0.
    #[validate(range(min = 1))]
    pub evse_id: u32,
    /// *(2.1)* True when power tolerance is accepted by EV.
    /// This value is taken from EVPowerProfile.PowerToleranceAcceptance in the ISO 15118-20 PowerDeliverReq message..
    #[serde(skip_serializing_if = "Option::is_none")]
    pub power_tolerance_acceptance: Option<bool>,
    /// *(2.1)* Id  of the _chargingSchedule_ that EV selected from the provided ChargingProfile.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub selected_charging_schedule_id: Option<u32>,
    /// Periods contained in the charging profile are relative to this point in time.
    #[serde(with = "datetime_rfc3339")]
    pub time_base: DateTime<Utc>,
}

static_assertions::assert_impl_all!(NotifyEVChargingScheduleRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyEVChargingScheduleResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: GenericStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(NotifyEVChargingScheduleResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
