// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::report_data::ReportDataType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyReportRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Timestamp of the moment this message was generated at the Charging Station.
    #[serde(with = "datetime_rfc3339")]
    pub generated_at: DateTime<Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub report_data: Option<Vec<ReportDataType>>,
    /// The id of the GetReportRequest  or GetBaseReportRequest that requested this report
    pub request_id: i32,
    /// Sequence number of this message. First message starts at 0.
    #[validate(range(min = 0))]
    pub seq_no: u32,
    /// “to be continued” indicator. Indicates whether another part of the report follows in an upcoming notifyReportRequest message. Default value when omitted is false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tbc: Option<bool>,
}

static_assertions::assert_impl_all!(NotifyReportRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyReportResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(NotifyReportResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
