// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::status_info::StatusInfoType;
use crate::v2_1::enumerations::energy_transfer_mode::EnergyTransferModeEnumType;
use crate::v2_1::enumerations::notify_allowed_energy_transfer_status::NotifyAllowedEnergyTransferStatusEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyAllowedEnergyTransferRequest {
    /// Modes of energy transfer that are accepted by CSMS.
    #[validate(length(min = 1))]
    pub allowed_energy_transfer: Vec<EnergyTransferModeEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The transaction for which the allowed energy transfer is allowed.
    #[validate(length(max = 36))]
    pub transaction_id: String,
}

static_assertions::assert_impl_all!(NotifyAllowedEnergyTransferRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyAllowedEnergyTransferResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: NotifyAllowedEnergyTransferStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(NotifyAllowedEnergyTransferResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
