// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyCustomerInformationRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// (Part of) the requested data. No format specified in which the data is returned. Should be human readable.
    #[validate(length(max = 512))]
    pub data: String,
    ///  Timestamp of the moment this message was generated at the Charging Station.
    #[serde(with = "datetime_rfc3339")]
    pub generated_at: DateTime<Utc>,
    /// The Id of the request.
    #[validate(range(min = 0))]
    pub request_id: u32,
    /// Sequence number of this message. First message starts at 0.
    #[validate(range(min = 0))]
    pub seq_no: u32,
    /// “to be continued” indicator. Indicates whether another part of the monitoringData follows in an upcoming notifyMonitoringReportRequest message. Default value when omitted is false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tbc: Option<bool>,
}

static_assertions::assert_impl_all!(NotifyCustomerInformationRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyCustomerInformationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(NotifyCustomerInformationResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
