// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::charging_needs::ChargingNeedsType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::status_info::StatusInfoType;
use crate::v2_1::enumerations::notify_ev_charging_needs_status::NotifyEVChargingNeedsStatusEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyEVChargingNeedsRequest {
    pub charging_needs: ChargingNeedsType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Defines the EVSE and connector to which the EV is connected. EvseId may not be 0.
    #[validate(range(min = 1))]
    pub evse_id: u32,
    /// Contains the maximum elements the EV supports for: +
    /// - ISO 15118-2: schedule tuples in SASchedule (both Pmax and Tariff). +
    /// - ISO 15118-20: PowerScheduleEntry, PriceRule and PriceLevelScheduleEntries.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub max_schedule_tuples: Option<u32>,
    /// *(2.1)* Time when EV charging needs were received. +
    /// Field can be added when charging station was offline when charging needs were received.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub timestamp: Option<DateTime<Utc>>,
}

static_assertions::assert_impl_all!(NotifyEVChargingNeedsRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyEVChargingNeedsResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: NotifyEVChargingNeedsStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(NotifyEVChargingNeedsResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
