// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::der_curve_get::DERCurveGetType;
use crate::v2_1::datatypes::enter_service_get::EnterServiceGetType;
use crate::v2_1::datatypes::fixed_pf_get::FixedPFGetType;
use crate::v2_1::datatypes::fixed_var_get::FixedVarGetType;
use crate::v2_1::datatypes::freq_droop_get::FreqDroopGetType;
use crate::v2_1::datatypes::gradient_get::GradientGetType;
use crate::v2_1::datatypes::limit_max_discharge_get::LimitMaxDischargeGetType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ReportDERControlRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub curve: Option<Vec<DERCurveGetType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub enter_service: Option<Vec<EnterServiceGetType>>,
    #[serde(rename = "fixedPFAbsorb")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub fixed_pf_absorb: Option<Vec<FixedPFGetType>>,
    #[serde(rename = "fixedPFInject")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub fixed_pf_inject: Option<Vec<FixedPFGetType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub fixed_var: Option<Vec<FixedVarGetType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub freq_droop: Option<Vec<FreqDroopGetType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub gradient: Option<Vec<GradientGetType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub limit_max_discharge: Option<Vec<LimitMaxDischargeGetType>>,
    /// RequestId from GetDERControlRequest.
    pub request_id: i32,
    /// To Be Continued. Default value when omitted: false. +
    /// False indicates that there are no further messages as part of this report.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tbc: Option<bool>,
}

static_assertions::assert_impl_all!(ReportDERControlRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

/// This message has no parameters.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ReportDERControlResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(ReportDERControlResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
