// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::message_info::MessageInfoType;
use crate::v2_1::datatypes::status_info::StatusInfoType;
use crate::v2_1::enumerations::display_message_status::DisplayMessageStatusEnumType;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetDisplayMessageRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub message: MessageInfoType,
}

static_assertions::assert_impl_all!(SetDisplayMessageRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetDisplayMessageResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: DisplayMessageStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(SetDisplayMessageResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
