// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::der_curve::DERCurveType;
use crate::v2_1::datatypes::enter_service::EnterServiceType;
use crate::v2_1::datatypes::fixed_pf::FixedPFType;
use crate::v2_1::datatypes::fixed_var::FixedVarType;
use crate::v2_1::datatypes::freq_droop::FreqDroopType;
use crate::v2_1::datatypes::gradient::GradientType;
use crate::v2_1::datatypes::limit_max_discharge::LimitMaxDischargeType;
use crate::v2_1::datatypes::status_info::StatusInfoType;
use crate::v2_1::enumerations::der_control::DERControlEnumType;
use crate::v2_1::enumerations::der_control_status::DERControlStatusEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetDERControlRequest {
    /// Unique id of this control, e.g. UUID
    #[validate(length(max = 36))]
    pub control_id: String,
    pub control_type: DERControlEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub curve: Option<DERCurveType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enter_service: Option<EnterServiceType>,
    #[serde(rename = "fixedPFAbsorb")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_pf_absorb: Option<FixedPFType>,
    #[serde(rename = "fixedPFInject")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_pf_inject: Option<FixedPFType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_var: Option<FixedVarType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub freq_droop: Option<FreqDroopType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gradient: Option<GradientType>,
    /// True if this is a default DER control
    pub is_default: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit_max_discharge: Option<LimitMaxDischargeType>,
}

static_assertions::assert_impl_all!(SetDERControlRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetDERControlResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: DERControlStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
    /// List of controlIds that are superseded as a result of setting this control.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 24))]
    pub superseded_ids: Option<Vec<String>>,
}

static_assertions::assert_impl_all!(SetDERControlResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
