// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::connector_status::ConnectorStatusEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct StatusNotificationRequest {
    /// The id of the connector within the EVSE for which the status is reported.
    #[validate(range(min = 0))]
    pub connector_id: u32,
    pub connector_status: ConnectorStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The id of the EVSE to which the connector belongs for which the the status is reported.
    #[validate(range(min = 0))]
    pub evse_id: u32,
    /// The time for which the status is reported.
    #[serde(with = "datetime_rfc3339")]
    pub timestamp: DateTime<Utc>,
}

static_assertions::assert_impl_all!(StatusNotificationRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct StatusNotificationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(StatusNotificationResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
