// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::cost_details::CostDetailsType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::evse::EVSEType;
use crate::v2_1::datatypes::id_token::IdTokenType;
use crate::v2_1::datatypes::id_token_info::IdTokenInfoType;
use crate::v2_1::datatypes::message_content::MessageContentType;
use crate::v2_1::datatypes::meter_value::MeterValueType;
use crate::v2_1::datatypes::transaction::TransactionType;
use crate::v2_1::datatypes::transaction_limit::TransactionLimitType;
use crate::v2_1::enumerations::preconditioning_status::PreconditioningStatusEnumType;
use crate::v2_1::enumerations::transaction_event::TransactionEventEnumType;
use crate::v2_1::enumerations::trigger_reason::TriggerReasonEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TransactionEventRequest {
    /// The maximum current of the connected cable in Ampere (A).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cable_max_current: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_details: Option<CostDetailsType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub event_type: TransactionEventEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evse: Option<EVSEType>,
    /// *(2.1)* True when EVSE electronics are in sleep mode for this transaction. Default value (when absent) is false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evse_sleep: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_token: Option<IdTokenType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub meter_value: Option<Vec<MeterValueType>>,
    /// If the Charging Station is able to report the number of phases used, then it SHALL provide it.
    /// When omitted the CSMS may be able to determine the number of phases used as follows: +
    /// 1: The numberPhases in the currently used ChargingSchedule. +
    /// 2: The number of phases provided via device management.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 3))]
    pub number_of_phases_used: Option<u8>,
    /// Indication that this transaction event happened when the Charging Station was offline. Default = false, meaning: the event occurred when the Charging Station was online.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offline: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preconditioning_status: Option<PreconditioningStatusEnumType>,
    /// This contains the Id of the reservation that terminates as a result of this transaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub reservation_id: Option<u32>,
    /// Incremental sequence number, helps with determining if all messages of a transaction have been received.
    #[validate(range(min = 0))]
    pub seq_no: u32,
    /// The date and time at which this transaction event occurred.
    #[serde(with = "datetime_rfc3339")]
    pub timestamp: DateTime<Utc>,
    pub transaction_info: TransactionType,
    pub trigger_reason: TriggerReasonEnumType,
}

static_assertions::assert_impl_all!(TransactionEventRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TransactionEventResponse {
    /// Priority from a business point of view. Default priority is 0, The range is from -9 to 9. Higher values indicate a higher priority. The chargingPriority in &lt;&lt;transactioneventresponse,TransactionEventResponse&gt;&gt; is temporarily, so it may not be set in the &lt;&lt;cmn_idtokeninfotype,IdTokenInfoType&gt;&gt; afterwards. Also the chargingPriority in &lt;&lt;transactioneventresponse,TransactionEventResponse&gt;&gt; has a higher priority than the one in &lt;&lt;cmn_idtokeninfotype,IdTokenInfoType&gt;&gt;.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub charging_priority: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_token_info: Option<IdTokenInfoType>,
    /// When _eventType_ of TransactionEventRequest is Updated, then this value contains the running cost. When _eventType_ of TransactionEventRequest is Ended, then this contains the final total cost of this transaction, including taxes, in the currency configured with the Configuration Variable: Currency. Absence of this value does not imply that the transaction was free. To indicate a free transaction, the CSMS SHALL send a value of 0.00.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub total_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_limit: Option<TransactionLimitType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_personal_message: Option<MessageContentType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 4))]
    pub updated_personal_message_extra: Option<Vec<MessageContentType>>,
}

static_assertions::assert_impl_all!(TransactionEventResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
