// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::unpublish_firmware_status::UnpublishFirmwareStatusEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct UnpublishFirmwareRequest {
    /// The MD5 checksum over the entire firmware file as a hexadecimal string of length 32.
    #[validate(length(max = 32))]
    pub checksum: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(UnpublishFirmwareRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct UnpublishFirmwareResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: UnpublishFirmwareStatusEnumType,
}

static_assertions::assert_impl_all!(UnpublishFirmwareResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
