// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::charging_schedule_update::ChargingScheduleUpdateType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::status_info::StatusInfoType;
use crate::v2_1::enumerations::charging_profile_status::ChargingProfileStatusEnumType;

/// Id of dynamic charging profile to update.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct UpdateDynamicScheduleRequest {
    /// Id of charging profile to update.
    pub charging_profile_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub schedule_update: ChargingScheduleUpdateType,
}

static_assertions::assert_impl_all!(UpdateDynamicScheduleRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct UpdateDynamicScheduleResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: ChargingProfileStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(UpdateDynamicScheduleResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
