// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;

/// AC_ Charging_ Parameters
/// urn:x-oca:ocpp:uid:2:233250
/// EV AC charging parameters.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ACChargingParametersType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// AC_ Charging_ Parameters. Energy_ Amount. Energy_ Amount
    /// urn:x-oca:ocpp:uid:1:569211
    /// Amount of energy requested (in Wh). This includes energy required for preconditioning.
    pub energy_amount: i32,
    /// AC_ Charging_ Parameters. EV_ Max. Current
    /// urn:x-oca:ocpp:uid:1:569213
    /// Maximum current (amps) supported by the electric vehicle (per phase). Includes cable capacity.
    pub ev_max_current: i32,
    /// AC_ Charging_ Parameters. EV_ Max. Voltage
    /// urn:x-oca:ocpp:uid:1:569214
    /// Maximum voltage supported by the electric vehicle
    pub ev_max_voltage: i32,
    /// AC_ Charging_ Parameters. EV_ Min. Current
    /// urn:x-oca:ocpp:uid:1:569212
    /// Minimum current (amps) supported by the electric vehicle (per phase).
    pub ev_min_current: i32,
}

static_assertions::assert_impl_all!(ACChargingParametersType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
