// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::apn_authentication::APNAuthenticationEnumType;
use validator::Validate;

/// APN
/// urn:x-oca:ocpp:uid:2:233134
/// Collection of configuration data needed to make a data-connection over a cellular network.
///
/// NOTE: When asking a GSM modem to dial in, it is possible to specify which mobile operator should be used. This can be done with the mobile country code (MCC) in combination with a mobile network code (MNC). Example: If your preferred network is Vodafone Netherlands, the MCC=204 and the MNC=04 which means the key PreferredNetwork = 20404 Some modems allows to specify a preferred network, which means, if this network is not available, a different network is used. If you specify UseOnlyPreferredNetwork and this network is not available, the modem will not dial in.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct APNType {
    /// APN. APN. URI
    /// urn:x-oca:ocpp:uid:1:568814
    /// The Access Point Name as an URL.
    #[validate(length(max = 512))]
    pub apn: String,
    pub apn_authentication: APNAuthenticationEnumType,
    /// APN. APN. Password
    /// urn:x-oca:ocpp:uid:1:568819
    /// APN Password.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 20))]
    pub apn_password: Option<String>,
    /// APN. APN. User_ Name
    /// urn:x-oca:ocpp:uid:1:568818
    /// APN username.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 20))]
    pub apn_user_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// APN. Preferred_ Network. Mobile_ Network_ ID
    /// urn:x-oca:ocpp:uid:1:568822
    /// Preferred network, written as MCC and MNC concatenated. See note.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 6))]
    pub preferred_network: Option<String>,
    /// APN. SIMPIN. PIN_ Code
    /// urn:x-oca:ocpp:uid:1:568821
    /// SIM card pin code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sim_pin: Option<i32>,
    /// APN. Use_ Only_ Preferred_ Network. Indicator
    /// urn:x-oca:ocpp:uid:1:568824
    /// Default: false. Use only the preferred Network, do
    /// not dial in when not available. See Note.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub use_only_preferred_network: Option<bool>,
}

static_assertions::assert_impl_all!(APNType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
