// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::certificate_hash_data::CertificateHashDataType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::get_certificate_id_use::GetCertificateIdUseEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct CertificateHashDataChainType {
    pub certificate_hash_data: CertificateHashDataType,
    pub certificate_type: GetCertificateIdUseEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 4))]
    pub child_certificate_hash_data: Option<Vec<CertificateHashDataType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(CertificateHashDataChainType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
