// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::modem::ModemType;
use validator::Validate;

/// Charge_ Point
/// urn:x-oca:ocpp:uid:2:233122
/// The physical system where an Electrical Vehicle (EV) can be charged.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingStationType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// This contains the firmware version of the Charging Station.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub firmware_version: Option<String>,
    /// Device. Model. CI20_ Text
    /// urn:x-oca:ocpp:uid:1:569325
    /// Defines the model of the device.
    #[validate(length(max = 20))]
    pub model: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modem: Option<ModemType>,
    /// Device. Serial_ Number. Serial_ Number
    /// urn:x-oca:ocpp:uid:1:569324
    /// Vendor-specific device identifier.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 25))]
    pub serial_number: Option<String>,
    /// Identifies the vendor (not necessarily in a unique manner).
    #[validate(length(max = 50))]
    pub vendor_name: String,
}

static_assertions::assert_impl_all!(ChargingStationType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
