// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::ac_charging_parameters::ACChargingParametersType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::dc_charging_parameters::DCChargingParametersType;
use crate::v2_0_1::enumerations::energy_transfer_mode::EnergyTransferModeEnumType;
use crate::v2_0_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;

/// Charging_ Needs
/// urn:x-oca:ocpp:uid:2:233249
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingNeedsType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ac_charging_parameters: Option<ACChargingParametersType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_charging_parameters: Option<DCChargingParametersType>,
    /// Charging_ Needs. Departure_ Time. Date_ Time
    /// urn:x-oca:ocpp:uid:1:569223
    /// Estimated departure time of the EV.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub departure_time: Option<DateTime<Utc>>,
    pub requested_energy_transfer: EnergyTransferModeEnumType,
}

static_assertions::assert_impl_all!(ChargingNeedsType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
