// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::charging_schedule_period::ChargingSchedulePeriodType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::sales_tariff::SalesTariffType;
use crate::v2_0_1::enumerations::charging_rate_unit::ChargingRateUnitEnumType;
use crate::v2_0_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

/// Charging_ Schedule
/// urn:x-oca:ocpp:uid:2:233256
/// Charging schedule structure defines a list of charging periods, as used in: GetCompositeSchedule.conf and ChargingProfile.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingScheduleType {
    pub charging_rate_unit: ChargingRateUnitEnumType,
    #[validate(length(min = 1, max = 1024))]
    pub charging_schedule_period: Vec<ChargingSchedulePeriodType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Charging_ Schedule. Duration. Elapsed_ Time
    /// urn:x-oca:ocpp:uid:1:569236
    /// Duration of the charging schedule in seconds. If the duration is left empty, the last period will continue indefinitely or until end of the transaction if chargingProfilePurpose = TxProfile.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// Identifies the ChargingSchedule.
    pub id: i32,
    /// Charging_ Schedule. Min_ Charging_ Rate. Numeric
    /// urn:x-oca:ocpp:uid:1:569239
    /// Minimum charging rate supported by the EV. The unit of measure is defined by the chargingRateUnit. This parameter is intended to be used by a local smart charging algorithm to optimize the power allocation for in the case a charging process is inefficient at lower charging rates. Accepts at most one digit fraction (e.g. 8.1)
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charging_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sales_tariff: Option<SalesTariffType>,
    /// Charging_ Schedule. Start_ Schedule. Date_ Time
    /// urn:x-oca:ocpp:uid:1:569237
    /// Starting point of an absolute schedule. If absent the schedule will be relative to start of charging.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub start_schedule: Option<DateTime<Utc>>,
}

static_assertions::assert_impl_all!(ChargingScheduleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
