// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;

/// Charging_ Schedule_ Period
/// urn:x-oca:ocpp:uid:2:233257
/// Charging schedule period structure defines a time period in a charging schedule.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingSchedulePeriodType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Charging_ Schedule_ Period. Limit. Measure
    /// urn:x-oca:ocpp:uid:1:569241
    /// Charging rate limit during the schedule period, in the applicable chargingRateUnit, for example in Amperes (A) or Watts (W). Accepts at most one digit fraction (e.g. 8.1).
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub limit: Decimal,
    /// Charging_ Schedule_ Period. Number_ Phases. Counter
    /// urn:x-oca:ocpp:uid:1:569242
    /// The number of phases that can be used for charging. If a number of phases is needed, numberPhases=3 will be assumed unless another number is given.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub number_phases: Option<i32>,
    /// Values: 1..3, Used if numberPhases=1 and if the EVSE is capable of switching the phase connected to the EV, i.e. ACPhaseSwitchingSupported is defined and true. It’s not allowed unless both conditions above are true. If both conditions are true, and phaseToUse is omitted, the Charging Station / EVSE will make the selection on its own.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phase_to_use: Option<i32>,
    /// Charging_ Schedule_ Period. Start_ Period. Elapsed_ Time
    /// urn:x-oca:ocpp:uid:1:569240
    /// Start of the period, in seconds from the start of schedule. The value of StartPeriod also defines the stop time of the previous period.
    pub start_period: i32,
}

static_assertions::assert_impl_all!(ChargingSchedulePeriodType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
