// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::charging_schedule::ChargingScheduleType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::charging_profile_kind::ChargingProfileKindEnumType;
use crate::v2_0_1::enumerations::charging_profile_purpose::ChargingProfilePurposeEnumType;
use crate::v2_0_1::enumerations::recurrency_kind::RecurrencyKindEnumType;
use crate::v2_0_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// Charging_ Profile
/// urn:x-oca:ocpp:uid:2:233255
/// A ChargingProfile consists of ChargingSchedule, describing the amount of power or current that can be delivered per time interval.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingProfileType {
    pub charging_profile_kind: ChargingProfileKindEnumType,
    pub charging_profile_purpose: ChargingProfilePurposeEnumType,
    #[validate(length(min = 1, max = 3))]
    pub charging_schedule: Vec<ChargingScheduleType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Identified_ Object. MRID. Numeric_ Identifier
    /// urn:x-enexis:ecdm:uid:1:569198
    /// Id of ChargingProfile.
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recurrency_kind: Option<RecurrencyKindEnumType>,
    /// Charging_ Profile. Stack_ Level. Counter
    /// urn:x-oca:ocpp:uid:1:569230
    /// Value determining level in hierarchy stack of profiles. Higher values have precedence over lower values. Lowest level is 0.
    pub stack_level: i32,
    /// SHALL only be included if ChargingProfilePurpose is set to TxProfile. The transactionId is used to match the profile to a specific transaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 36))]
    pub transaction_id: Option<String>,
    /// Charging_ Profile. Valid_ From. Date_ Time
    /// urn:x-oca:ocpp:uid:1:569234
    /// Point in time at which the profile starts to be valid. If absent, the profile is valid as soon as it is received by the Charging Station.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub valid_from: Option<DateTime<Utc>>,
    /// Charging_ Profile. Valid_ To. Date_ Time
    /// urn:x-oca:ocpp:uid:1:569235
    /// Point in time at which the profile stops to be valid. If absent, the profile is valid until it is replaced by another profile.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub valid_to: Option<DateTime<Utc>>,
}

static_assertions::assert_impl_all!(ChargingProfileType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
