// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::charging_limit_source::ChargingLimitSourceEnumType;

/// Charging_ Limit
/// urn:x-enexis:ecdm:uid:2:234489
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingLimitType {
    pub charging_limit_source: ChargingLimitSourceEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Charging_ Limit. Is_ Grid_ Critical. Indicator
    /// urn:x-enexis:ecdm:uid:1:570847
    /// Indicates whether the charging limit is critical for the grid.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_grid_critical: Option<bool>,
}

static_assertions::assert_impl_all!(ChargingLimitType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
