// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::cost::CostType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;
use validator::Validate;

/// Consumption_ Cost
/// urn:x-oca:ocpp:uid:2:233259
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ConsumptionCostType {
    #[validate(length(min = 1, max = 3))]
    pub cost: Vec<CostType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Consumption_ Cost. Start_ Value. Numeric
    /// urn:x-oca:ocpp:uid:1:569246
    /// The lowest level of consumption that defines the starting point of this consumption block. The block interval extends to the start of the next interval.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub start_value: Decimal,
}

static_assertions::assert_impl_all!(ConsumptionCostType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
