// @generated by codegen — do not edit by hand.

use validator::Validate;

/// This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct CustomDataType {
    #[validate(length(max = 255))]
    pub vendor_id: String,
}

static_assertions::assert_impl_all!(CustomDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
