// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

/// DC_ Charging_ Parameters
/// urn:x-oca:ocpp:uid:2:233251
/// EV DC charging parameters
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct DCChargingParametersType {
    /// DC_ Charging_ Parameters. Bulk_ SOC. Percentage
    /// urn:x-oca:ocpp:uid:1:569222
    /// Percentage of SoC at which the EV considers a fast charging process to end. (possible values: 0 - 100)
    #[serde(rename = "bulkSoC")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub bulk_soc: Option<u8>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// DC_ Charging_ Parameters. Energy_ Amount. Energy_ Amount
    /// urn:x-oca:ocpp:uid:1:569217
    /// Amount of energy requested (in Wh). This inludes energy required for preconditioning.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub energy_amount: Option<i32>,
    /// DC_ Charging_ Parameters. EV_ Energy_ Capacity. Numeric
    /// urn:x-oca:ocpp:uid:1:569220
    /// Capacity of the electric vehicle battery (in Wh)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ev_energy_capacity: Option<i32>,
    /// DC_ Charging_ Parameters. EV_ Max. Current
    /// urn:x-oca:ocpp:uid:1:569215
    /// Maximum current (amps) supported by the electric vehicle. Includes cable capacity.
    pub ev_max_current: i32,
    /// DC_ Charging_ Parameters. EV_ Max. Power
    /// urn:x-oca:ocpp:uid:1:569218
    /// Maximum power (in W) supported by the electric vehicle. Required for DC charging.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ev_max_power: Option<i32>,
    /// DC_ Charging_ Parameters. EV_ Max. Voltage
    /// urn:x-oca:ocpp:uid:1:569216
    /// Maximum voltage supported by the electric vehicle
    pub ev_max_voltage: i32,
    /// DC_ Charging_ Parameters. Full_ SOC. Percentage
    /// urn:x-oca:ocpp:uid:1:569221
    /// Percentage of SoC at which the EV considers the battery fully charged. (possible values: 0 - 100)
    #[serde(rename = "fullSoC")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub full_soc: Option<u8>,
    /// DC_ Charging_ Parameters. State_ Of_ Charge. Numeric
    /// urn:x-oca:ocpp:uid:1:569219
    /// Energy available in the battery (in percent of the battery capacity)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub state_of_charge: Option<u8>,
}

static_assertions::assert_impl_all!(DCChargingParametersType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
