// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;

/// EVSE
/// urn:x-oca:ocpp:uid:2:233123
/// Electric Vehicle Supply Equipment
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct EVSEType {
    /// An id to designate a specific connector (on an EVSE) by connector index number.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub connector_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Identified_ Object. MRID. Numeric_ Identifier
    /// urn:x-enexis:ecdm:uid:1:569198
    /// EVSE Identifier. This contains a number (&gt; 0) designating an EVSE of the Charging Station.
    pub id: i32,
}

static_assertions::assert_impl_all!(EVSEType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
