// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// Firmware
/// urn:x-enexis:ecdm:uid:2:233291
/// Represents a copy of the firmware that can be loaded/updated on the Charging Station.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct FirmwareType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Firmware. Install. Date_ Time
    /// urn:x-enexis:ecdm:uid:1:569462
    /// Date and time at which the firmware shall be installed.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub install_date_time: Option<DateTime<Utc>>,
    /// Firmware. Location. URI
    /// urn:x-enexis:ecdm:uid:1:569460
    /// URI defining the origin of the firmware.
    #[validate(length(max = 512))]
    pub location: String,
    /// Firmware. Retrieve. Date_ Time
    /// urn:x-enexis:ecdm:uid:1:569461
    /// Date and time at which the firmware shall be retrieved.
    #[serde(with = "datetime_rfc3339")]
    pub retrieve_date_time: DateTime<Utc>,
    /// Firmware. Signature. Signature
    /// urn:x-enexis:ecdm:uid:1:569464
    /// Base64 encoded firmware signature.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 800))]
    pub signature: Option<String>,
    /// Certificate with which the firmware was signed.
    /// PEM encoded X.509 certificate.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 5500))]
    pub signing_certificate: Option<String>,
}

static_assertions::assert_impl_all!(FirmwareType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
