// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::id_token::IdTokenType;
use crate::v2_0_1::datatypes::message_content::MessageContentType;
use crate::v2_0_1::enumerations::authorization_status::AuthorizationStatusEnumType;
use crate::v2_0_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// ID_ Token
/// urn:x-oca:ocpp:uid:2:233247
/// Contains status information about an identifier.
/// It is advised to not stop charging for a token that expires during charging, as ExpiryDate is only used for caching purposes. If ExpiryDate is not given, the status has no end date.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct IdTokenInfoType {
    /// ID_ Token. Expiry. Date_ Time
    /// urn:x-oca:ocpp:uid:1:569373
    /// Date and Time after which the token must be considered invalid.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub cache_expiry_date_time: Option<DateTime<Utc>>,
    /// Priority from a business point of view. Default priority is 0, The range is from -9 to 9. Higher values indicate a higher priority. The chargingPriority in &lt;&lt;transactioneventresponse,TransactionEventResponse&gt;&gt; overrules this one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub charging_priority: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Only used when the IdToken is only valid for one or more specific EVSEs, not for the entire Charging Station.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub evse_id: Option<Vec<i32>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_id_token: Option<IdTokenType>,
    /// ID_ Token. Language1. Language_ Code
    /// urn:x-oca:ocpp:uid:1:569374
    /// Preferred user interface language of identifier user. Contains a language code as defined in &lt;&lt;ref-RFC5646,[RFC5646]&gt;&gt;.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 8))]
    pub language1: Option<String>,
    /// ID_ Token. Language2. Language_ Code
    /// urn:x-oca:ocpp:uid:1:569375
    /// Second preferred user interface language of identifier user. Don’t use when language1 is omitted, has to be different from language1. Contains a language code as defined in &lt;&lt;ref-RFC5646,[RFC5646]&gt;&gt;.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 8))]
    pub language2: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub personal_message: Option<MessageContentType>,
    pub status: AuthorizationStatusEnumType,
}

static_assertions::assert_impl_all!(IdTokenInfoType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
