// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// Log
/// urn:x-enexis:ecdm:uid:2:233373
/// Generic class for the configuration of logging entries.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct LogParametersType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Log. Latest_ Timestamp. Date_ Time
    /// urn:x-enexis:ecdm:uid:1:569482
    /// This contains the date and time of the latest logging information to include in the diagnostics.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub latest_timestamp: Option<DateTime<Utc>>,
    /// Log. Oldest_ Timestamp. Date_ Time
    /// urn:x-enexis:ecdm:uid:1:569477
    /// This contains the date and time of the oldest logging information to include in the diagnostics.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub oldest_timestamp: Option<DateTime<Utc>>,
    /// Log. Remote_ Location. URI
    /// urn:x-enexis:ecdm:uid:1:569484
    /// The URL of the location at the remote system where the log should be stored.
    #[validate(length(max = 512))]
    pub remote_location: String,
}

static_assertions::assert_impl_all!(LogParametersType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
