// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::component::ComponentType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::message_content::MessageContentType;
use crate::v2_0_1::enumerations::message_priority::MessagePriorityEnumType;
use crate::v2_0_1::enumerations::message_state::MessageStateEnumType;
use crate::v2_0_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// Message_ Info
/// urn:x-enexis:ecdm:uid:2:233264
/// Contains message details, for a message to be displayed on a Charging Station.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct MessageInfoType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display: Option<ComponentType>,
    /// Message_ Info. End. Date_ Time
    /// urn:x-enexis:ecdm:uid:1:569257
    /// Until what date-time should this message be shown, after this date/time this message SHALL be removed.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub end_date_time: Option<DateTime<Utc>>,
    /// Identified_ Object. MRID. Numeric_ Identifier
    /// urn:x-enexis:ecdm:uid:1:569198
    /// Master resource identifier, unique within an exchange context. It is defined within the OCPP context as a positive Integer value (greater or equal to zero).
    pub id: i32,
    pub message: MessageContentType,
    pub priority: MessagePriorityEnumType,
    /// Message_ Info. Start. Date_ Time
    /// urn:x-enexis:ecdm:uid:1:569256
    /// From what date-time should this message be shown. If omitted: directly.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub start_date_time: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<MessageStateEnumType>,
    /// During which transaction shall this message be shown.
    /// Message SHALL be removed by the Charging Station after transaction has
    /// ended.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 36))]
    pub transaction_id: Option<String>,
}

static_assertions::assert_impl_all!(MessageInfoType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
