// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::sampled_value::SampledValueType;
use crate::v2_0_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// Meter_ Value
/// urn:x-oca:ocpp:uid:2:233265
/// Collection of one or more sampled values in MeterValuesRequest and TransactionEvent. All sampled values in a MeterValue are sampled at the same point in time.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct MeterValueType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[validate(length(min = 1))]
    pub sampled_value: Vec<SampledValueType>,
    /// Meter_ Value. Timestamp. Date_ Time
    /// urn:x-oca:ocpp:uid:1:569259
    /// Timestamp for measured value(s).
    #[serde(with = "datetime_rfc3339")]
    pub timestamp: DateTime<Utc>,
}

static_assertions::assert_impl_all!(MeterValueType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
