// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::apn::APNType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::vpn::VPNType;
use crate::v2_0_1::enumerations::ocpp_interface::OCPPInterfaceEnumType;
use crate::v2_0_1::enumerations::ocpp_transport::OCPPTransportEnumType;
use crate::v2_0_1::enumerations::ocpp_version::OCPPVersionEnumType;
use validator::Validate;

/// Communication_ Function
/// urn:x-oca:ocpp:uid:2:233304
/// The NetworkConnectionProfile defines the functional and technical parameters of a communication link.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NetworkConnectionProfileType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub apn: Option<APNType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Duration in seconds before a message send by the Charging Station via this network connection times-out.
    /// The best setting depends on the underlying network and response times of the CSMS.
    /// If you are looking for a some guideline: use 30 seconds as a starting point.
    pub message_timeout: i32,
    /// Communication_ Function. OCPP_ Central_ System_ URL. URI
    /// urn:x-oca:ocpp:uid:1:569357
    /// URL of the CSMS(s) that this Charging Station  communicates with.
    #[validate(length(max = 512))]
    pub ocpp_csms_url: String,
    pub ocpp_interface: OCPPInterfaceEnumType,
    pub ocpp_transport: OCPPTransportEnumType,
    pub ocpp_version: OCPPVersionEnumType,
    /// This field specifies the security profile used when connecting to the CSMS with this NetworkConnectionProfile.
    pub security_profile: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vpn: Option<VPNType>,
}

static_assertions::assert_impl_all!(NetworkConnectionProfileType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
