// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::hash_algorithm::HashAlgorithmEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct OCSPRequestDataType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub hash_algorithm: HashAlgorithmEnumType,
    /// Hashed value of the issuers public key
    #[validate(length(max = 128))]
    pub issuer_key_hash: String,
    /// Hashed value of the Issuer DN (Distinguished Name).
    #[validate(length(max = 128))]
    pub issuer_name_hash: String,
    /// This contains the responder URL (Case insensitive).
    #[serde(rename = "responderURL")]
    #[validate(length(max = 512))]
    pub responder_url: String,
    /// The serial number of the certificate.
    #[validate(length(max = 40))]
    pub serial_number: String,
}

static_assertions::assert_impl_all!(OCSPRequestDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
