// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;

/// Relative_ Timer_ Interval
/// urn:x-oca:ocpp:uid:2:233270
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct RelativeTimeIntervalType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Relative_ Timer_ Interval. Duration. Elapsed_ Time
    /// urn:x-oca:ocpp:uid:1:569280
    /// Duration of the interval, in seconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// Relative_ Timer_ Interval. Start. Elapsed_ Time
    /// urn:x-oca:ocpp:uid:1:569279
    /// Start of the interval, in seconds from NOW.
    pub start: i32,
}

static_assertions::assert_impl_all!(RelativeTimeIntervalType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
