// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::component::ComponentType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::variable::VariableType;
use crate::v2_0_1::datatypes::variable_attribute::VariableAttributeType;
use crate::v2_0_1::datatypes::variable_characteristics::VariableCharacteristicsType;
use validator::Validate;

/// Class to report components, variables and variable attributes and characteristics.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ReportDataType {
    pub component: ComponentType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub variable: VariableType,
    #[validate(length(min = 1, max = 4))]
    pub variable_attribute: Vec<VariableAttributeType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variable_characteristics: Option<VariableCharacteristicsType>,
}

static_assertions::assert_impl_all!(ReportDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
