// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::sales_tariff_entry::SalesTariffEntryType;
use validator::Validate;

/// Sales_ Tariff
/// urn:x-oca:ocpp:uid:2:233272
/// NOTE: This dataType is based on dataTypes from &lt;&lt;ref-ISOIEC15118-2,ISO 15118-2&gt;&gt;.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct SalesTariffType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Identified_ Object. MRID. Numeric_ Identifier
    /// urn:x-enexis:ecdm:uid:1:569198
    /// SalesTariff identifier used to identify one sales tariff. An SAID remains a unique identifier for one schedule throughout a charging session.
    pub id: i32,
    /// Sales_ Tariff. Num_ E_ Price_ Levels. Counter
    /// urn:x-oca:ocpp:uid:1:569284
    /// Defines the overall number of distinct price levels used across all provided SalesTariff elements.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_e_price_levels: Option<i32>,
    /// Sales_ Tariff. Sales. Tariff_ Description
    /// urn:x-oca:ocpp:uid:1:569283
    /// A human readable title/short description of the sales tariff e.g. for HMI display purposes.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 32))]
    pub sales_tariff_description: Option<String>,
    #[validate(length(min = 1, max = 1024))]
    pub sales_tariff_entry: Vec<SalesTariffEntryType>,
}

static_assertions::assert_impl_all!(SalesTariffType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
