// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::charging_state::ChargingStateEnumType;
use crate::v2_0_1::enumerations::reason::ReasonEnumType;
use validator::Validate;

/// Transaction
/// urn:x-oca:ocpp:uid:2:233318
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TransactionType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub charging_state: Option<ChargingStateEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The ID given to remote start request (&lt;&lt;requeststarttransactionrequest, RequestStartTransactionRequest&gt;&gt;. This enables to CSMS to match the started transaction to the given start request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remote_start_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stopped_reason: Option<ReasonEnumType>,
    /// Transaction. Time_ Spent_ Charging. Elapsed_ Time
    /// urn:x-oca:ocpp:uid:1:569415
    /// Contains the total time that energy flowed from EVSE to EV during the transaction (in seconds). Note that timeSpentCharging is smaller or equal to the duration of the transaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_spent_charging: Option<i32>,
    /// This contains the Id of the transaction.
    #[validate(length(max = 36))]
    pub transaction_id: String,
}

static_assertions::assert_impl_all!(TransactionType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
