// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::data::DataEnumType;
use rust_decimal::Decimal;
use validator::Validate;

/// Fixed read-only parameters of a variable.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct VariableCharacteristicsType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub data_type: DataEnumType,
    /// Maximum possible value of this variable. When the datatype of this Variable is String, OptionList, SequenceList or MemberList, this field defines the maximum length of the (CSV) string.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_limit: Option<Decimal>,
    /// Minimum possible value of this variable.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_limit: Option<Decimal>,
    /// Flag indicating if this variable supports monitoring.
    pub supports_monitoring: bool,
    /// Unit of the variable. When the transmitted value has a unit, this field SHALL be included.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 16))]
    pub unit: Option<String>,
    /// Allowed values when variable is Option/Member/SequenceList.
    ///
    /// * OptionList: The (Actual) Variable value must be a single value from the reported (CSV) enumeration list.
    ///
    /// * MemberList: The (Actual) Variable value  may be an (unordered) (sub-)set of the reported (CSV) valid values list.
    ///
    /// * SequenceList: The (Actual) Variable value  may be an ordered (priority, etc)  (sub-)set of the reported (CSV) valid values.
    ///
    /// This is a comma separated list.
    ///
    /// The Configuration Variable &lt;&lt;configkey-configuration-value-size,ConfigurationValueSize&gt;&gt; can be used to limit SetVariableData.attributeValue and VariableCharacteristics.valueList. The max size of these values will always remain equal.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 1000))]
    pub values_list: Option<String>,
}

static_assertions::assert_impl_all!(VariableCharacteristicsType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
