// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::vpn::VPNEnumType;
use validator::Validate;

/// VPN
/// urn:x-oca:ocpp:uid:2:233268
/// VPN Configuration settings
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct VPNType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// VPN. Group. Group_ Name
    /// urn:x-oca:ocpp:uid:1:569274
    /// VPN group.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 20))]
    pub group: Option<String>,
    /// VPN. Key. VPN_ Key
    /// urn:x-oca:ocpp:uid:1:569276
    /// VPN shared secret.
    #[validate(length(max = 255))]
    pub key: String,
    /// VPN. Password. Password
    /// urn:x-oca:ocpp:uid:1:569275
    /// VPN Password.
    #[validate(length(max = 20))]
    pub password: String,
    /// VPN. Server. URI
    /// urn:x-oca:ocpp:uid:1:569272
    /// VPN Server Address
    #[validate(length(max = 512))]
    pub server: String,
    #[serde(rename = "type")]
    pub kind: VPNEnumType,
    /// VPN. User. User_ Name
    /// urn:x-oca:ocpp:uid:1:569273
    /// VPN User
    #[validate(length(max = 20))]
    pub user: String,
}

static_assertions::assert_impl_all!(VPNType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
