// @generated by codegen — do not edit by hand.

//! # Implementation of the OCPP v2_1 Specification
//!
//! Generated from the official OCPP JSON schemas.

/// datatypes
pub mod datatypes;

/// enumerations
pub mod enumerations;

/// messages
pub mod messages;

/// helper functions
pub mod helpers;
