// @generated by codegen — do not edit by hand.

use rust_decimal::Decimal;
use std::sync::OnceLock;

use regex::Regex;
use validator::ValidationError;

static REGEX: OnceLock<Regex> = OnceLock::new();

/// Helper function to validate identifierString.
///
/// # identifierString
/// This is a case-insensitive dataType and can only contain characters from the
/// following character set: `a-z`, `A-Z`, `0-9`, `'*'`, `'-'`, `'_'`, `'='`,
/// `':'`, `'+'`, `'|'`, `'@'`, `'.'`
pub fn validate_identifier_string(s: &str) -> Result<(), ValidationError> {
    let res = REGEX
        .get_or_init(|| Regex::new(r"^[a-zA-Z0-9*+=:|@._-]*$").unwrap())
        .is_match(s);

    match res {
        true => Ok(()),
        false => Err(ValidationError::new("Not a valid identifierString")),
    }
}

/// Validates that a Decimal lies within the schema-declared range.
pub fn validate_decimal_min_0_max_100(value: &Decimal) -> Result<(), ValidationError> {
    let min = Decimal::try_from(0_f64).unwrap();
    if *value < min {
        return Err(ValidationError::new("value below minimum"));
    }
    let max = Decimal::try_from(100_f64).unwrap();
    if *value > max {
        return Err(ValidationError::new("value above maximum"));
    }
    Ok(())
}

/// Validates that a Decimal lies within the schema-declared range.
pub fn validate_decimal_max_0(value: &Decimal) -> Result<(), ValidationError> {
    let max = Decimal::try_from(0_f64).unwrap();
    if *value > max {
        return Err(ValidationError::new("value above maximum"));
    }
    Ok(())
}
