// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::id_token::IdTokenType;
use crate::v2_0_1::datatypes::id_token_info::IdTokenInfoType;
use crate::v2_0_1::datatypes::ocsp_request_data::OCSPRequestDataType;
use crate::v2_0_1::enumerations::authorize_certificate_status::AuthorizeCertificateStatusEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct AuthorizeRequest {
    /// The X.509 certificated presented by EV and encoded in PEM format.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 5500))]
    pub certificate: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub id_token: IdTokenType,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 4))]
    pub iso_15118_certificate_hash_data: Option<Vec<OCSPRequestDataType>>,
}

static_assertions::assert_impl_all!(AuthorizeRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct AuthorizeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certificate_status: Option<AuthorizeCertificateStatusEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub id_token_info: IdTokenInfoType,
}

static_assertions::assert_impl_all!(AuthorizeResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
