// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::status_info::StatusInfoType;
use crate::v2_0_1::enumerations::cancel_reservation_status::CancelReservationStatusEnumType;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct CancelReservationRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Id of the reservation to cancel.
    pub reservation_id: i32,
}

static_assertions::assert_impl_all!(CancelReservationRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct CancelReservationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: CancelReservationStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(CancelReservationResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
