// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::composite_schedule::CompositeScheduleType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::status_info::StatusInfoType;
use crate::v2_0_1::enumerations::charging_rate_unit::ChargingRateUnitEnumType;
use crate::v2_0_1::enumerations::generic_status::GenericStatusEnumType;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct GetCompositeScheduleRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub charging_rate_unit: Option<ChargingRateUnitEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Length of the requested schedule in seconds.
    pub duration: i32,
    /// The ID of the EVSE for which the schedule is requested. When evseid=0, the Charging Station will calculate the expected consumption for the grid connection.
    pub evse_id: i32,
}

static_assertions::assert_impl_all!(GetCompositeScheduleRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct GetCompositeScheduleResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schedule: Option<CompositeScheduleType>,
    pub status: GenericStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(GetCompositeScheduleResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
