// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::status_info::StatusInfoType;
use crate::v2_0_1::enumerations::certificate_action::CertificateActionEnumType;
use crate::v2_0_1::enumerations::iso15118ev_certificate_status::Iso15118EVCertificateStatusEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct Get15118EVCertificateRequest {
    pub action: CertificateActionEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Raw CertificateInstallationReq request from EV, Base64 encoded.
    #[validate(length(max = 5600))]
    pub exi_request: String,
    /// Schema version currently used for the 15118 session between EV and Charging Station. Needed for parsing of the EXI stream by the CSMS.
    #[validate(length(max = 50))]
    pub iso_15118_schema_version: String,
}

static_assertions::assert_impl_all!(Get15118EVCertificateRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct Get15118EVCertificateResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Raw CertificateInstallationRes response for the EV, Base64 encoded.
    #[validate(length(max = 5600))]
    pub exi_response: String,
    pub status: Iso15118EVCertificateStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(Get15118EVCertificateResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
