// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::enumerations::upload_log_status::UploadLogStatusEnumType;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct LogStatusNotificationRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The request id that was provided in GetLogRequest that started this log upload. This field is mandatory,
    /// unless the message was triggered by a TriggerMessageRequest AND there is no log upload ongoing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_id: Option<i32>,
    pub status: UploadLogStatusEnumType,
}

static_assertions::assert_impl_all!(LogStatusNotificationRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct LogStatusNotificationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(LogStatusNotificationResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
