// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::charging_limit::ChargingLimitType;
use crate::v2_0_1::datatypes::charging_schedule::ChargingScheduleType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyChargingLimitRequest {
    pub charging_limit: ChargingLimitType,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub charging_schedule: Option<Vec<ChargingScheduleType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The charging schedule contained in this notification applies to an EVSE. evseId must be &gt; 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evse_id: Option<i32>,
}

static_assertions::assert_impl_all!(NotifyChargingLimitRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct NotifyChargingLimitResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
}

static_assertions::assert_impl_all!(NotifyChargingLimitResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
