// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::authorization_data::AuthorizationData;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::status_info::StatusInfoType;
use crate::v2_0_1::enumerations::send_local_list_status::SendLocalListStatusEnumType;
use crate::v2_0_1::enumerations::update::UpdateEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct SendLocalListRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub local_authorization_list: Option<Vec<AuthorizationData>>,
    pub update_type: UpdateEnumType,
    /// In case of a full update this is the version number of the full list. In case of a differential update it is the version number of the list after the update has been applied.
    pub version_number: i32,
}

static_assertions::assert_impl_all!(SendLocalListRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SendLocalListResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: SendLocalListStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(SendLocalListResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
