// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::charging_profile::ChargingProfileType;
use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::status_info::StatusInfoType;
use crate::v2_0_1::enumerations::charging_profile_status::ChargingProfileStatusEnumType;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetChargingProfileRequest {
    pub charging_profile: ChargingProfileType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// For TxDefaultProfile an evseId=0 applies the profile to each individual evse. For ChargingStationMaxProfile and ChargingStationExternalConstraints an evseId=0 contains an overal limit for the whole Charging Station.
    pub evse_id: i32,
}

static_assertions::assert_impl_all!(SetChargingProfileRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetChargingProfileResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub status: ChargingProfileStatusEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_info: Option<StatusInfoType>,
}

static_assertions::assert_impl_all!(SetChargingProfileResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
