// @generated by codegen — do not edit by hand.

use crate::v2_0_1::datatypes::custom_data::CustomDataType;
use crate::v2_0_1::datatypes::set_monitoring_data::SetMonitoringDataType;
use crate::v2_0_1::datatypes::set_monitoring_result::SetMonitoringResultType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetVariableMonitoringRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[validate(length(min = 1))]
    pub set_monitoring_data: Vec<SetMonitoringDataType>,
}

static_assertions::assert_impl_all!(SetVariableMonitoringRequest: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetVariableMonitoringResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[validate(length(min = 1))]
    pub set_monitoring_result: Vec<SetMonitoringResultType>,
}

static_assertions::assert_impl_all!(SetVariableMonitoringResponse: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
