// @generated by codegen — do not edit by hand.

/// APN. APN_ Authentication. APN_ Authentication_ Code
/// urn:x-oca:ocpp:uid:1:568828
/// Authentication method.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum APNAuthenticationEnumType {
    #[default]
    CHAP,
    NONE,
    PAP,
    AUTO,
}

static_assertions::assert_impl_all!(APNAuthenticationEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
