// @generated by codegen — do not edit by hand.

/// Attribute type for which value is requested. When absent, default Actual is assumed.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum AttributeEnumType {
    #[default]
    Actual,
    Target,
    MinSet,
    MaxSet,
}

static_assertions::assert_impl_all!(AttributeEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
