// @generated by codegen — do not edit by hand.

/// ID_ Token. Status. Authorization_ Status
/// urn:x-oca:ocpp:uid:1:569372
/// Current status of the ID Token.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum AuthorizationStatusEnumType {
    #[default]
    Accepted,
    Blocked,
    ConcurrentTx,
    Expired,
    Invalid,
    NoCredit,
    NotAllowedTypeEVSE,
    NotAtThisLocation,
    NotAtThisTime,
    Unknown,
}

static_assertions::assert_impl_all!(AuthorizationStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
