// @generated by codegen — do not edit by hand.

/// This indicates the success or failure of the canceling of a reservation by CSMS.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum CancelReservationStatusEnumType {
    #[default]
    Accepted,
    Rejected,
}

static_assertions::assert_impl_all!(CancelReservationStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
