// @generated by codegen — do not edit by hand.

/// Defines whether certificate needs to be installed or updated.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum CertificateActionEnumType {
    #[default]
    Install,
    Update,
}

static_assertions::assert_impl_all!(CertificateActionEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
