// @generated by codegen — do not edit by hand.

/// Returns whether certificate signing has been accepted, otherwise rejected.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum CertificateSignedStatusEnumType {
    #[default]
    Accepted,
    Rejected,
}

static_assertions::assert_impl_all!(CertificateSignedStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
