// @generated by codegen — do not edit by hand.

/// Charging_ Schedule. Charging_ Rate_ Unit. Charging_ Rate_ Unit_ Code
/// urn:x-oca:ocpp:uid:1:569238
/// The unit of measure Limit is expressed in.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ChargingRateUnitEnumType {
    #[default]
    W,
    A,
}

static_assertions::assert_impl_all!(ChargingRateUnitEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
