// @generated by codegen — do not edit by hand.

/// Returns whether the Charging Station has been able to process the message successfully. This does not guarantee the schedule will be followed to the letter. There might be other constraints the Charging Station may need to take into account.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ChargingProfileStatusEnumType {
    #[default]
    Accepted,
    Rejected,
}

static_assertions::assert_impl_all!(ChargingProfileStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
