// @generated by codegen — do not edit by hand.

/// Transaction. State. Transaction_ State_ Code
/// urn:x-oca:ocpp:uid:1:569419
/// Current charging state, is required when state
/// has changed.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ChargingStateEnumType {
    #[default]
    Charging,
    EVConnected,
    SuspendedEV,
    SuspendedEVSE,
    Idle,
}

static_assertions::assert_impl_all!(ChargingStateEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
