// @generated by codegen — do not edit by hand.

/// Charging_ Limit. Charging_ Limit_ Source. Charging_ Limit_ Source_ Code
/// urn:x-enexis:ecdm:uid:1:570845
/// Represents the source of the charging limit.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ChargingLimitSourceEnumType {
    #[default]
    EMS,
    Other,
    SO,
    CSO,
}

static_assertions::assert_impl_all!(ChargingLimitSourceEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
