// @generated by codegen — do not edit by hand.

/// Indicates if the Charging Station was able to execute the request.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ClearChargingProfileStatusEnumType {
    #[default]
    Accepted,
    Unknown,
}

static_assertions::assert_impl_all!(ClearChargingProfileStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
