// @generated by codegen — do not edit by hand.

/// Accepted if the Charging Station has executed the request, otherwise rejected.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ClearCacheStatusEnumType {
    #[default]
    Accepted,
    Rejected,
}

static_assertions::assert_impl_all!(ClearCacheStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
