// @generated by codegen — do not edit by hand.

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ComponentCriterionEnumType {
    #[default]
    Active,
    Available,
    Enabled,
    Problem,
}

static_assertions::assert_impl_all!(ComponentCriterionEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
