// @generated by codegen — do not edit by hand.

/// This contains the current status of the Connector.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ConnectorStatusEnumType {
    #[default]
    Available,
    Occupied,
    Reserved,
    Unavailable,
    Faulted,
}

static_assertions::assert_impl_all!(ConnectorStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
