// @generated by codegen — do not edit by hand.

/// Indicates whether the request was accepted.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum CustomerInformationStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    Invalid,
}

static_assertions::assert_impl_all!(CustomerInformationStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
