// @generated by codegen — do not edit by hand.

/// This indicates the success or failure of the data transfer.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum DataTransferStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    UnknownMessageId,
    UnknownVendorId,
}

static_assertions::assert_impl_all!(DataTransferStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
