// @generated by codegen — do not edit by hand.

/// Charging Station indicates if it can process the request.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum DeleteCertificateStatusEnumType {
    #[default]
    Accepted,
    Failed,
    NotFound,
}

static_assertions::assert_impl_all!(DeleteCertificateStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
