// @generated by codegen — do not edit by hand.

/// This indicates whether the Charging Station is able to display the message.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum DisplayMessageStatusEnumType {
    #[default]
    Accepted,
    NotSupportedMessageFormat,
    Rejected,
    NotSupportedPriority,
    NotSupportedState,
    UnknownTransaction,
}

static_assertions::assert_impl_all!(DisplayMessageStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
