// @generated by codegen — do not edit by hand.

/// Specifies the event notification type of the message.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum EventNotificationEnumType {
    #[default]
    HardWiredNotification,
    HardWiredMonitor,
    PreconfiguredMonitor,
    CustomMonitor,
}

static_assertions::assert_impl_all!(EventNotificationEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
