// @generated by codegen — do not edit by hand.

/// This field indicates whether the Charging Station was able to accept the request.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum GenericDeviceModelStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    NotSupported,
    EmptyResultSet,
}

static_assertions::assert_impl_all!(GenericDeviceModelStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
