// @generated by codegen — do not edit by hand.

/// Indicates if the Charging Station has Display Messages that match the request criteria in the &lt;&lt;getdisplaymessagesrequest,GetDisplayMessagesRequest&gt;&gt;
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum GetDisplayMessagesStatusEnumType {
    #[default]
    Accepted,
    Unknown,
}

static_assertions::assert_impl_all!(GetDisplayMessagesStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
