// @generated by codegen — do not edit by hand.

/// Charging Station indicates if it can process the request.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum GetInstalledCertificateStatusEnumType {
    #[default]
    Accepted,
    NotFound,
}

static_assertions::assert_impl_all!(GetInstalledCertificateStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
