// @generated by codegen — do not edit by hand.

/// Result status of getting the variable.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum GetVariableStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    UnknownComponent,
    UnknownVariable,
    NotSupportedAttributeType,
}

static_assertions::assert_impl_all!(GetVariableStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
