// @generated by codegen — do not edit by hand.

/// This indicates whether the Charging Station is able to process this request and will send &lt;&lt;reportchargingprofilesrequest, ReportChargingProfilesRequest&gt;&gt; messages.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum GetChargingProfileStatusEnumType {
    #[default]
    Accepted,
    NoProfiles,
}

static_assertions::assert_impl_all!(GetChargingProfileStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
