// @generated by codegen — do not edit by hand.

/// This indicates whether the charging station was able to retrieve the OCSP certificate status.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum GetCertificateStatusEnumType {
    #[default]
    Accepted,
    Failed,
}

static_assertions::assert_impl_all!(GetCertificateStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
