// @generated by codegen — do not edit by hand.

/// Used algorithms for the hashes provided.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum HashAlgorithmEnumType {
    #[default]
    SHA256,
    SHA384,
    SHA512,
}

static_assertions::assert_impl_all!(HashAlgorithmEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
