// @generated by codegen — do not edit by hand.

/// Indicates the certificate type that is sent.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum InstallCertificateUseEnumType {
    #[default]
    V2GRootCertificate,
    MORootCertificate,
    CSMSRootCertificate,
    ManufacturerRootCertificate,
}

static_assertions::assert_impl_all!(InstallCertificateUseEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
