// @generated by codegen — do not edit by hand.

/// Indicates whether the message was processed properly.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum Iso15118EVCertificateStatusEnumType {
    #[default]
    Accepted,
    Failed,
}

static_assertions::assert_impl_all!(Iso15118EVCertificateStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
