// @generated by codegen — do not edit by hand.

/// This contains the type of log file that the Charging Station
/// should send.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum LogEnumType {
    #[default]
    DiagnosticsLog,
    SecurityLog,
}

static_assertions::assert_impl_all!(LogEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
