// @generated by codegen — do not edit by hand.

/// Message_ Info. Priority. Message_ Priority_ Code
/// urn:x-enexis:ecdm:uid:1:569253
/// With what priority should this message be shown
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum MessagePriorityEnumType {
    #[default]
    AlwaysFront,
    InFront,
    NormalCycle,
}

static_assertions::assert_impl_all!(MessagePriorityEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
