// @generated by codegen — do not edit by hand.

/// Message_ Info. State. Message_ State_ Code
/// urn:x-enexis:ecdm:uid:1:569254
/// During what state should this message be shown. When omitted this message should be shown in any state of the Charging Station.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum MessageStateEnumType {
    #[default]
    Charging,
    Faulted,
    Idle,
    Unavailable,
}

static_assertions::assert_impl_all!(MessageStateEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
