// @generated by codegen — do not edit by hand.

/// Defines the mutability of this attribute. Default is ReadWrite when omitted.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum MutabilityEnumType {
    ReadOnly,
    WriteOnly,
    #[default]
    ReadWrite,
}

static_assertions::assert_impl_all!(MutabilityEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
