// @generated by codegen — do not edit by hand.

/// Communication_ Function. OCPP_ Version. OCPP_ Version_ Code
/// urn:x-oca:ocpp:uid:1:569355
/// Defines the OCPP version used for this communication function.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum OCPPVersionEnumType {
    #[default]
    OCPP12,
    OCPP15,
    OCPP16,
    OCPP20,
}

static_assertions::assert_impl_all!(OCPPVersionEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
