// @generated by codegen — do not edit by hand.

/// Applicable Network Interface.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum OCPPInterfaceEnumType {
    #[default]
    Wired0,
    Wired1,
    Wired2,
    Wired3,
    Wireless0,
    Wireless1,
    Wireless2,
    Wireless3,
}

static_assertions::assert_impl_all!(OCPPInterfaceEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
