// @generated by codegen — do not edit by hand.

/// This contains the progress status of the publishfirmware
/// installation.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum PublishFirmwareStatusEnumType {
    #[default]
    Idle,
    DownloadScheduled,
    Downloading,
    Downloaded,
    Published,
    DownloadFailed,
    DownloadPaused,
    InvalidChecksum,
    ChecksumVerified,
    PublishFailed,
}

static_assertions::assert_impl_all!(PublishFirmwareStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
