// @generated by codegen — do not edit by hand.

/// Transaction. Stopped_ Reason. EOT_ Reason_ Code
/// urn:x-oca:ocpp:uid:1:569413
/// This contains the reason why the transaction was stopped. MAY only be omitted when Reason is "Local".
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ReasonEnumType {
    #[default]
    DeAuthorized,
    EmergencyStop,
    EnergyLimitReached,
    EVDisconnected,
    GroundFault,
    ImmediateReset,
    Local,
    LocalOutOfCredit,
    MasterPass,
    Other,
    OvercurrentFault,
    PowerLoss,
    PowerQuality,
    Reboot,
    Remote,
    SOCLimitReached,
    StoppedByEV,
    TimeLimitReached,
    Timeout,
}

static_assertions::assert_impl_all!(ReasonEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
