// @generated by codegen — do not edit by hand.

/// Charging_ Profile. Recurrency_ Kind. Recurrency_ Kind_ Code
/// urn:x-oca:ocpp:uid:1:569233
/// Indicates the start point of a recurrence.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum RecurrencyKindEnumType {
    #[default]
    Daily,
    Weekly,
}

static_assertions::assert_impl_all!(RecurrencyKindEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
