// @generated by codegen — do not edit by hand.

/// This contains whether the Charging Station has been registered
/// within the CSMS.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum RegistrationStatusEnumType {
    #[default]
    Accepted,
    Pending,
    Rejected,
}

static_assertions::assert_impl_all!(RegistrationStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
