// @generated by codegen — do not edit by hand.

/// This field specifies the report base.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ReportBaseEnumType {
    #[default]
    ConfigurationInventory,
    FullInventory,
    SummaryInventory,
}

static_assertions::assert_impl_all!(ReportBaseEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
