// @generated by codegen — do not edit by hand.

/// Status indicating whether the Charging Station accepts the request to start a transaction.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum RequestStartStopStatusEnumType {
    #[default]
    Accepted,
    Rejected,
}

static_assertions::assert_impl_all!(RequestStartStopStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
