// @generated by codegen — do not edit by hand.

/// This indicates whether the Charging Station is able to perform the reset.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ResetStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    Scheduled,
}

static_assertions::assert_impl_all!(ResetStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
