// @generated by codegen — do not edit by hand.

/// Result of operation.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum SetNetworkProfileStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    Failed,
}

static_assertions::assert_impl_all!(SetNetworkProfileStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
