// @generated by codegen — do not edit by hand.

/// Status is OK if a value could be returned. Otherwise this will indicate the reason why a value could not be returned.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum SetMonitoringStatusEnumType {
    #[default]
    Accepted,
    UnknownComponent,
    UnknownVariable,
    UnsupportedMonitorType,
    Rejected,
    Duplicate,
}

static_assertions::assert_impl_all!(SetMonitoringStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
