// @generated by codegen — do not edit by hand.

/// This contains the type of this event.
/// The first TransactionEvent of a transaction SHALL contain: "Started" The last TransactionEvent of a transaction SHALL contain: "Ended" All others SHALL contain: "Updated"
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum TransactionEventEnumType {
    #[default]
    Ended,
    Started,
    Updated,
}

static_assertions::assert_impl_all!(TransactionEventEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
