// @generated by codegen — do not edit by hand.

/// This indicates whether the Charging Station has unlocked the connector.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum UnlockStatusEnumType {
    #[default]
    Unlocked,
    UnlockFailed,
    OngoingAuthorizedTransaction,
    UnknownConnector,
}

static_assertions::assert_impl_all!(UnlockStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
