// @generated by codegen — do not edit by hand.

/// This contains the type of update (full or differential) of this request.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum UpdateEnumType {
    #[default]
    Differential,
    Full,
}

static_assertions::assert_impl_all!(UpdateEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
