// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::additional_selected_services::AdditionalSelectedServicesType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::overstay_rule_list::OverstayRuleListType;
use crate::v2_1::datatypes::price_rule_stack::PriceRuleStackType;
use crate::v2_1::datatypes::rational_number::RationalNumberType;
use crate::v2_1::datatypes::tax_rule::TaxRuleType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// The AbsolutePriceScheduleType is modeled after the same type that is defined in ISO 15118-20, such that if it is supplied by an EMSP as a signed EXI message, the conversion from EXI to JSON (in OCPP) and back to EXI (for ISO 15118-20) does not change the digest and therefore does not invalidate the signature.
///
/// image::images/AbsolutePriceSchedule-Simple.png[]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct AbsolutePriceScheduleType {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 5))]
    pub additional_selected_services: Option<Vec<AdditionalSelectedServicesType>>,
    /// Currency according to ISO 4217.
    #[validate(length(max = 3))]
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// String that indicates what language is used for the human readable strings in the price schedule. Based on ISO 639.
    #[validate(length(max = 8))]
    pub language: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maximum_cost: Option<RationalNumberType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub minimum_cost: Option<RationalNumberType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overstay_rule_list: Option<OverstayRuleListType>,
    /// A string in URN notation which shall uniquely identify an algorithm that defines how to compute an energy fee sum for a specific power profile based on the EnergyFee information from the PriceRule elements.
    #[validate(length(max = 2000))]
    pub price_algorithm: String,
    #[validate(length(min = 1, max = 1024))]
    pub price_rule_stacks: Vec<PriceRuleStackType>,
    /// Description of the price schedule.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 160))]
    pub price_schedule_description: Option<String>,
    /// Unique ID of price schedule
    #[serde(rename = "priceScheduleID")]
    #[validate(range(min = 0))]
    pub price_schedule_id: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 10))]
    pub tax_rules: Option<Vec<TaxRuleType>>,
    /// Starting point of price schedule.
    #[serde(with = "datetime_rfc3339")]
    pub time_anchor: DateTime<Utc>,
}

static_assertions::assert_impl_all!(AbsolutePriceScheduleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
