// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;

/// EV AC charging parameters for ISO 15118-2
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ACChargingParametersType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Amount of energy requested (in Wh). This includes energy required for preconditioning.
    /// Relates to: +
    /// *ISO 15118-2*: AC_EVChargeParameterType: EAmount +
    /// *ISO 15118-20*: Dynamic/Scheduled_SEReqControlModeType: EVTargetEnergyRequest
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub energy_amount: Decimal,
    /// Maximum current (amps) supported by the electric vehicle (per phase). Includes cable capacity.
    /// Relates to: +
    /// *ISO 15118-2*: AC_EVChargeParameterType: EVMaxCurrent
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub ev_max_current: Decimal,
    /// Maximum voltage supported by the electric vehicle.
    /// Relates to: +
    /// *ISO 15118-2*: AC_EVChargeParameterType: EVMaxVoltage
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub ev_max_voltage: Decimal,
    /// Minimum current (amps) supported by the electric vehicle (per phase).
    /// Relates to: +
    /// *ISO 15118-2*: AC_EVChargeParameterType: EVMinCurrent
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub ev_min_current: Decimal,
}

static_assertions::assert_impl_all!(ACChargingParametersType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
