// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::rational_number::RationalNumberType;
use validator::Validate;

/// Part of ISO 15118-20 price schedule.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct AdditionalSelectedServicesType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub service_fee: RationalNumberType,
    /// Human readable string to identify this service.
    #[validate(length(max = 80))]
    pub service_name: String,
}

static_assertions::assert_impl_all!(AdditionalSelectedServicesType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
