// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

/// *(2.1)* A generic address format.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct AddressType {
    /// Address line 1
    #[validate(length(max = 100))]
    pub address1: String,
    /// Address line 2
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 100))]
    pub address2: Option<String>,
    /// City
    #[validate(length(max = 100))]
    pub city: String,
    /// Country name
    #[validate(length(max = 50))]
    pub country: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Name of person/company
    #[validate(length(max = 50))]
    pub name: String,
    /// Postal code
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 20))]
    pub postal_code: Option<String>,
}

static_assertions::assert_impl_all!(AddressType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
