// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::helpers::datetime_rfc3339;
use crate::v2_1::helpers::validator::validate_decimal_min_0_max_100;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct BatteryDataType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Slot number where battery is inserted or removed.
    #[validate(range(min = 0))]
    pub evse_id: u32,
    /// Production date of battery.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub production_date: Option<DateTime<Utc>>,
    /// Serial number of battery.
    #[validate(length(max = 50))]
    pub serial_number: String,
    /// State of charge
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    #[validate(custom(function = "validate_decimal_min_0_max_100"))]
    pub so_c: Decimal,
    /// State of health
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    #[validate(custom(function = "validate_decimal_min_0_max_100"))]
    pub so_h: Decimal,
    /// Vendor-specific info from battery in undefined format.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 500))]
    pub vendor_info: Option<String>,
}

static_assertions::assert_impl_all!(BatteryDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
