// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::certificate_hash_data::CertificateHashDataType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::certificate_status::CertificateStatusEnumType;
use crate::v2_1::enumerations::certificate_status_source::CertificateStatusSourceEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;

/// Revocation status of certificate
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct CertificateStatusType {
    pub certificate_hash_data: CertificateHashDataType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(with = "datetime_rfc3339")]
    pub next_update: DateTime<Utc>,
    pub source: CertificateStatusSourceEnumType,
    pub status: CertificateStatusEnumType,
}

static_assertions::assert_impl_all!(CertificateStatusType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
