// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::certificate_hash_data::CertificateHashDataType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::certificate_status_source::CertificateStatusSourceEnumType;
use validator::Validate;

/// Data necessary to request the revocation status of a certificate.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct CertificateStatusRequestInfoType {
    pub certificate_hash_data: CertificateHashDataType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub source: CertificateStatusSourceEnumType,
    /// URL(s) of _source_.
    #[validate(length(min = 1, max = 5))]
    pub urls: Vec<String>,
}

static_assertions::assert_impl_all!(CertificateStatusRequestInfoType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
