// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::v2_x_freq_watt_point::V2XFreqWattPointType;
use crate::v2_1::datatypes::v2_x_signal_watt_point::V2XSignalWattPointType;
use crate::v2_1::enumerations::operation_mode::OperationModeEnumType;
use crate::v2_1::helpers::validator::validate_decimal_max_0;
use rust_decimal::Decimal;
use validator::Validate;

/// Charging schedule period structure defines a time period in a charging schedule. It is used in: CompositeScheduleType and in ChargingScheduleType. When used in a NotifyEVChargingScheduleRequest only _startPeriod_, _limit_, _limit_L2_, _limit_L3_ are relevant.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingSchedulePeriodType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// *(2.1)* Limit in _chargingRateUnit_ that the EV is allowed to discharge with. Note, these are negative values in order to be consistent with _setpoint_, which can be positive and negative.  +
    /// For AC this field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    #[validate(custom(function = "validate_decimal_max_0"))]
    pub discharge_limit: Option<Decimal>,
    /// *(2.1)* Limit in _chargingRateUnit_ on phase L2 that the EV is allowed to discharge with.
    #[serde(rename = "dischargeLimit_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    #[validate(custom(function = "validate_decimal_max_0"))]
    pub discharge_limit_l2: Option<Decimal>,
    /// *(2.1)* Limit in _chargingRateUnit_ on phase L3 that the EV is allowed to discharge with.
    #[serde(rename = "dischargeLimit_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    #[validate(custom(function = "validate_decimal_max_0"))]
    pub discharge_limit_l3: Option<Decimal>,
    /// *(2.1)* If true, the EVSE must turn off power electronics/modules associated with this transaction. Default value when absent is false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evse_sleep: Option<bool>,
    /// Optional only when not required by the _operationMode_, as in CentralSetpoint, ExternalSetpoint, ExternalLimits, LocalFrequency,  LocalLoadBalancing. +
    /// Charging rate limit during the schedule period, in the applicable _chargingRateUnit_.
    /// This SHOULD be a non-negative value; a negative value is only supported for backwards compatibility with older systems that use a negative value to specify a discharging limit.
    /// When using _chargingRateUnit_ = `W`, this field represents the sum of the power of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub limit: Option<Decimal>,
    /// *(2.1)* Charging rate limit on phase L2  in the applicable _chargingRateUnit_.
    #[serde(rename = "limit_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub limit_l2: Option<Decimal>,
    /// *(2.1)* Charging rate limit on phase L3  in the applicable _chargingRateUnit_.
    #[serde(rename = "limit_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub limit_l3: Option<Decimal>,
    /// The number of phases that can be used for charging. +
    /// For a DC EVSE this field should be omitted. +
    /// For an AC EVSE a default value of _numberPhases_ = 3 will be assumed if the field is absent.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 3))]
    pub number_phases: Option<u8>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation_mode: Option<OperationModeEnumType>,
    /// Values: 1..3, Used if numberPhases=1 and if the EVSE is capable of switching the phase connected to the EV, i.e. ACPhaseSwitchingSupported is defined and true. It’s not allowed unless both conditions above are true. If both conditions are true, and phaseToUse is omitted, the Charging Station / EVSE will make the selection on its own.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 3))]
    pub phase_to_use: Option<u8>,
    /// *(2.1)* If  true, the EV should attempt to keep the BMS preconditioned for this time interval.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preconditioning_request: Option<bool>,
    /// *(2.1)* Setpoint in _chargingRateUnit_ that the EV should follow as close as possible. Use negative values for discharging. +
    /// When a limit and/or _dischargeLimit_ are given the overshoot when following _setpoint_ must remain within these values.
    /// This field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint: Option<Decimal>,
    /// *(2.1)* Setpoint for reactive power (or current) in _chargingRateUnit_ that the EV should follow as closely as possible. Positive values for inductive, negative for capacitive reactive power or current.  +
    /// This field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_reactive: Option<Decimal>,
    /// *(2.1)* Setpoint for reactive power (or current) in _chargingRateUnit_ that the EV should follow on phase L2 as closely as possible.
    #[serde(rename = "setpointReactive_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_reactive_l2: Option<Decimal>,
    /// *(2.1)* Setpoint for reactive power (or current) in _chargingRateUnit_ that the EV should follow on phase L3 as closely as possible.
    #[serde(rename = "setpointReactive_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_reactive_l3: Option<Decimal>,
    /// *(2.1)* Setpoint in _chargingRateUnit_ that the EV should follow on phase L2 as close as possible.
    #[serde(rename = "setpoint_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_l2: Option<Decimal>,
    /// *(2.1)* Setpoint in _chargingRateUnit_ that the EV should follow on phase L3 as close as possible.
    #[serde(rename = "setpoint_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_l3: Option<Decimal>,
    /// Start of the period, in seconds from the start of schedule. The value of StartPeriod also defines the stop time of the previous period.
    pub start_period: i32,
    /// *(2.1)* Power value that, when present, is used as a baseline on top of which values from _v2xFreqWattCurve_ and _v2xSignalWattCurve_ are added.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub v2x_baseline: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 20))]
    pub v2x_freq_watt_curve: Option<Vec<V2XFreqWattPointType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 20))]
    pub v2x_signal_watt_curve: Option<Vec<V2XSignalWattPointType>>,
}

static_assertions::assert_impl_all!(ChargingSchedulePeriodType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
