// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::charging_schedule::ChargingScheduleType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::charging_profile_kind::ChargingProfileKindEnumType;
use crate::v2_1::enumerations::charging_profile_purpose::ChargingProfilePurposeEnumType;
use crate::v2_1::enumerations::recurrency_kind::RecurrencyKindEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// A ChargingProfile consists of 1 to 3 ChargingSchedules with a list of ChargingSchedulePeriods, describing the amount of power or current that can be delivered per time interval.
///
/// image::images/ChargingProfile-Simple.png[]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingProfileType {
    pub charging_profile_kind: ChargingProfileKindEnumType,
    pub charging_profile_purpose: ChargingProfilePurposeEnumType,
    #[validate(length(min = 1, max = 3))]
    pub charging_schedule: Vec<ChargingScheduleType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// *(2.1)*  Interval in seconds after receipt of last update, when to request a profile update by sending a PullDynamicScheduleUpdateRequest message.
    ///     A value of 0 or no value means that no update interval applies. +
    ///     Only relevant in a dynamic charging profile.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dyn_update_interval: Option<i32>,
    /// *(2.1)* Time at which limits or setpoints in this charging profile were last updated by a PullDynamicScheduleUpdateRequest or UpdateDynamicScheduleRequest or by an external actor. +
    ///     Only relevant in a dynamic charging profile.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub dyn_update_time: Option<DateTime<Utc>>,
    /// Id of ChargingProfile. Unique within charging station. Id can have a negative value. This is useful to distinguish charging profiles from an external actor (external constraints) from charging profiles received from CSMS.
    pub id: i32,
    /// *(2.1)* When set to true this charging profile will not be valid anymore after being offline for more than _maxOfflineDuration_. +
    ///     When absent defaults to false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invalid_after_offline_duration: Option<bool>,
    /// *(2.1)* Period in seconds that this charging profile remains valid after the Charging Station has gone offline. After this period the charging profile becomes invalid for as long as it is offline and the Charging Station reverts back to a valid profile with a lower stack level.
    /// If _invalidAfterOfflineDuration_ is true, then this charging profile will become permanently invalid.
    /// A value of 0 means that the charging profile is immediately invalid while offline. When the field is absent, then  no timeout applies and the charging profile remains valid when offline.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_offline_duration: Option<i32>,
    /// *(2.1)* ISO 15118-20 signature for all price schedules in _chargingSchedules_. +
    /// Note: for 256-bit elliptic curves (like secp256k1) the ECDSA signature is 512 bits (64 bytes) and for 521-bit curves (like secp521r1) the signature is 1042 bits. This equals 131 bytes, which can be encoded as base64 in 176 bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 256))]
    pub price_schedule_signature: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recurrency_kind: Option<RecurrencyKindEnumType>,
    /// Value determining level in hierarchy stack of profiles. Higher values have precedence over lower values. Lowest level is 0.
    #[validate(range(min = 0))]
    pub stack_level: u32,
    /// SHALL only be included if ChargingProfilePurpose is set to TxProfile in a SetChargingProfileRequest. The transactionId is used to match the profile to a specific transaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 36))]
    pub transaction_id: Option<String>,
    /// Point in time at which the profile starts to be valid. If absent, the profile is valid as soon as it is received by the Charging Station.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub valid_from: Option<DateTime<Utc>>,
    /// Point in time at which the profile stops to be valid. If absent, the profile is valid until it is replaced by another profile.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub valid_to: Option<DateTime<Utc>>,
}

static_assertions::assert_impl_all!(ChargingProfileType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
