// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::ac_charging_parameters::ACChargingParametersType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::dc_charging_parameters::DCChargingParametersType;
use crate::v2_1::datatypes::der_charging_parameters::DERChargingParametersType;
use crate::v2_1::datatypes::ev_energy_offer::EVEnergyOfferType;
use crate::v2_1::datatypes::v2_x_charging_parameters::V2XChargingParametersType;
use crate::v2_1::enumerations::control_mode::ControlModeEnumType;
use crate::v2_1::enumerations::energy_transfer_mode::EnergyTransferModeEnumType;
use crate::v2_1::enumerations::mobility_needs_mode::MobilityNeedsModeEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingNeedsType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ac_charging_parameters: Option<ACChargingParametersType>,
    /// *(2.1)* Modes of energy transfer that are marked as available by EV.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub available_energy_transfer: Option<Vec<EnergyTransferModeEnumType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub control_mode: Option<ControlModeEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_charging_parameters: Option<DCChargingParametersType>,
    /// Estimated departure time of the EV. +
    /// *ISO 15118-2:* AC/DC_EVChargeParameterType: DepartureTime +
    /// *ISO 15118-20:* Dynamic/Scheduled_SEReqControlModeType: DepartureTIme
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub departure_time: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub der_charging_parameters: Option<DERChargingParametersType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ev_energy_offer: Option<EVEnergyOfferType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mobility_needs_mode: Option<MobilityNeedsModeEnumType>,
    pub requested_energy_transfer: EnergyTransferModeEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub v2x_charging_parameters: Option<V2XChargingParametersType>,
}

static_assertions::assert_impl_all!(ChargingNeedsType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
