// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::helpers::validator::validate_decimal_max_0;
use rust_decimal::Decimal;
use validator::Validate;

/// Updates to a ChargingSchedulePeriodType for dynamic charging profiles.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingScheduleUpdateType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// *(2.1)* Limit in _chargingRateUnit_ that the EV is allowed to discharge with. Note, these are negative values in order to be consistent with _setpoint_, which can be positive and negative.  +
    /// For AC this field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    #[validate(custom(function = "validate_decimal_max_0"))]
    pub discharge_limit: Option<Decimal>,
    /// *(2.1)* Limit in _chargingRateUnit_ on phase L2 that the EV is allowed to discharge with.
    #[serde(rename = "dischargeLimit_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    #[validate(custom(function = "validate_decimal_max_0"))]
    pub discharge_limit_l2: Option<Decimal>,
    /// *(2.1)* Limit in _chargingRateUnit_ on phase L3 that the EV is allowed to discharge with.
    #[serde(rename = "dischargeLimit_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    #[validate(custom(function = "validate_decimal_max_0"))]
    pub discharge_limit_l3: Option<Decimal>,
    /// Optional only when not required by the _operationMode_, as in CentralSetpoint, ExternalSetpoint, ExternalLimits, LocalFrequency,  LocalLoadBalancing. +
    /// Charging rate limit during the schedule period, in the applicable _chargingRateUnit_.
    /// This SHOULD be a non-negative value; a negative value is only supported for backwards compatibility with older systems that use a negative value to specify a discharging limit.
    /// For AC this field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub limit: Option<Decimal>,
    /// *(2.1)* Charging rate limit on phase L2  in the applicable _chargingRateUnit_.
    #[serde(rename = "limit_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub limit_l2: Option<Decimal>,
    /// *(2.1)* Charging rate limit on phase L3  in the applicable _chargingRateUnit_.
    #[serde(rename = "limit_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub limit_l3: Option<Decimal>,
    /// *(2.1)* Setpoint in _chargingRateUnit_ that the EV should follow as close as possible. Use negative values for discharging. +
    /// When a limit and/or _dischargeLimit_ are given the overshoot when following _setpoint_ must remain within these values.
    /// This field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint: Option<Decimal>,
    /// *(2.1)* Setpoint for reactive power (or current) in _chargingRateUnit_ that the EV should follow as closely as possible. Positive values for inductive, negative for capacitive reactive power or current.  +
    /// This field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_reactive: Option<Decimal>,
    /// *(2.1)* Setpoint for reactive power (or current) in _chargingRateUnit_ that the EV should follow on phase L2 as closely as possible.
    #[serde(rename = "setpointReactive_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_reactive_l2: Option<Decimal>,
    /// *(2.1)* Setpoint for reactive power (or current) in _chargingRateUnit_ that the EV should follow on phase L3 as closely as possible.
    #[serde(rename = "setpointReactive_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_reactive_l3: Option<Decimal>,
    /// *(2.1)* Setpoint in _chargingRateUnit_ that the EV should follow on phase L2 as close as possible.
    #[serde(rename = "setpoint_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_l2: Option<Decimal>,
    /// *(2.1)* Setpoint in _chargingRateUnit_ that the EV should follow on phase L3 as close as possible.
    #[serde(rename = "setpoint_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub setpoint_l3: Option<Decimal>,
}

static_assertions::assert_impl_all!(ChargingScheduleUpdateType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
