// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::cost_dimension::CostDimensionType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// A ChargingPeriodType consists of a start time, and a list of possible values that influence this period, for example: amount of energy charged this period, maximum current during this period etc.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingPeriodType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub dimensions: Option<Vec<CostDimensionType>>,
    /// Start timestamp of charging period. A period ends when the next period starts. The last period ends when the session ends.
    #[serde(with = "datetime_rfc3339")]
    pub start_period: DateTime<Utc>,
    /// Unique identifier of the Tariff that was used to calculate cost. If not provided, then cost was calculated by some other means.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 60))]
    pub tariff_id: Option<String>,
}

static_assertions::assert_impl_all!(ChargingPeriodType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
