// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::absolute_price_schedule::AbsolutePriceScheduleType;
use crate::v2_1::datatypes::charging_schedule_period::ChargingSchedulePeriodType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::limit_at_so_c::LimitAtSoCType;
use crate::v2_1::datatypes::price_level_schedule::PriceLevelScheduleType;
use crate::v2_1::datatypes::sales_tariff::SalesTariffType;
use crate::v2_1::enumerations::charging_rate_unit::ChargingRateUnitEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

/// Charging schedule structure defines a list of charging periods, as used in: NotifyEVChargingScheduleRequest and ChargingProfileType. When used in a NotifyEVChargingScheduleRequest only _duration_ and _chargingSchedulePeriod_ are relevant and _chargingRateUnit_ must be 'W'. +
/// An ISO 15118-20 session may provide either an _absolutePriceSchedule_ or a _priceLevelSchedule_. An ISO 15118-2 session can only provide a_salesTariff_ element. The field _digestValue_ is used when price schedule or sales tariff are signed.
///
/// image::images/ChargingSchedule-Simple.png[]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ChargingScheduleType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub absolute_price_schedule: Option<AbsolutePriceScheduleType>,
    pub charging_rate_unit: ChargingRateUnitEnumType,
    #[validate(length(min = 1, max = 1024))]
    pub charging_schedule_period: Vec<ChargingSchedulePeriodType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// *(2.1)* Base64 encoded hash (SHA256 for ISO 15118-2, SHA512 for ISO 15118-20) of the EXI price schedule element. Used in signature.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 88))]
    pub digest_value: Option<String>,
    /// Duration of the charging schedule in seconds. If the duration is left empty, the last period will continue indefinitely or until end of the transaction in case startSchedule is absent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit_at_so_c: Option<LimitAtSoCType>,
    /// Minimum charging rate supported by the EV. The unit of measure is defined by the chargingRateUnit. This parameter is intended to be used by a local smart charging algorithm to optimize the power allocation for in the case a charging process is inefficient at lower charging rates.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charging_rate: Option<Decimal>,
    /// *(2.1)* Power tolerance when following EVPowerProfile.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub power_tolerance: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_level_schedule: Option<PriceLevelScheduleType>,
    /// *(2.1)* Defaults to 0. When _randomizedDelay_ not equals zero, then the start of each &lt;&lt;cmn_chargingscheduleperiodtype,ChargingSchedulePeriodType&gt;&gt; is delayed by a randomly chosen number of seconds between 0 and _randomizedDelay_.  Only allowed for TxProfile and TxDefaultProfile.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub randomized_delay: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sales_tariff: Option<SalesTariffType>,
    /// *(2.1)* Id of this element for referencing in a signature.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub signature_id: Option<u32>,
    /// Starting point of an absolute schedule or recurring schedule.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub start_schedule: Option<DateTime<Utc>>,
    /// *(2.1)* Defaults to false. When true, disregard time zone offset in dateTime fields of  _ChargingScheduleType_ and use unqualified local time at Charging Station instead.
    ///  This allows the same `Absolute` or `Recurring` charging profile to be used in both summer and winter time.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub use_local_time: Option<bool>,
}

static_assertions::assert_impl_all!(ChargingScheduleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
