// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::charging_schedule_period::ChargingSchedulePeriodType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::charging_rate_unit::ChargingRateUnitEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct CompositeScheduleType {
    pub charging_rate_unit: ChargingRateUnitEnumType,
    #[validate(length(min = 1))]
    pub charging_schedule_period: Vec<ChargingSchedulePeriodType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub duration: i32,
    #[validate(range(min = 0))]
    pub evse_id: u32,
    #[serde(with = "datetime_rfc3339")]
    pub schedule_start: DateTime<Utc>,
}

static_assertions::assert_impl_all!(CompositeScheduleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
