// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::component::ComponentType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::variable::VariableType;

/// Class to report components, variables and variable attributes and characteristics.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ComponentVariableType {
    pub component: ComponentType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variable: Option<VariableType>,
}

static_assertions::assert_impl_all!(ComponentVariableType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
