// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::periodic_event_stream_params::PeriodicEventStreamParamsType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct ConstantStreamDataType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Uniquely identifies the stream
    #[validate(range(min = 0))]
    pub id: u32,
    pub params: PeriodicEventStreamParamsType,
    /// Id of monitor used to report his event. It can be a preconfigured or hardwired monitor.
    #[validate(range(min = 0))]
    pub variable_monitoring_id: u32,
}

static_assertions::assert_impl_all!(ConstantStreamDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
