// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::cost_dimension::CostDimensionEnumType;
use rust_decimal::Decimal;

/// Volume consumed of cost dimension.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct CostDimensionType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(rename = "type")]
    pub kind: CostDimensionEnumType,
    /// Volume of the dimension consumed, measured according to the dimension type.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub volume: Decimal,
}

static_assertions::assert_impl_all!(CostDimensionType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
