// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::charging_period::ChargingPeriodType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::total_cost::TotalCostType;
use crate::v2_1::datatypes::total_usage::TotalUsageType;
use validator::Validate;

/// CostDetailsType contains the cost as calculated by Charging Station based on provided TariffType.
///
/// NOTE: Reservation is not shown as a _chargingPeriod_, because it took place outside of the transaction.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct CostDetailsType {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub charging_periods: Option<Vec<ChargingPeriodType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Optional human-readable reason text in case of failure to calculate.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 500))]
    pub failure_reason: Option<String>,
    /// If set to true, then Charging Station has failed to calculate the cost.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_to_calculate: Option<bool>,
    pub total_cost: TotalCostType,
    pub total_usage: TotalUsageType,
}

static_assertions::assert_impl_all!(CostDetailsType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
