// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;
use validator::Validate;

/// EV DC charging parameters for ISO 15118-2
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct DCChargingParametersType {
    /// Percentage of SoC at which the EV considers a fast charging process to end. (possible values: 0 - 100)
    /// Relates to: +
    /// *ISO 15118-2*: DC_EVChargeParameterType: BulkSOC
    #[serde(rename = "bulkSoC")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub bulk_soc: Option<u8>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Amount of energy requested (in Wh). This inludes energy required for preconditioning.
    /// Relates to: +
    /// *ISO 15118-2*: DC_EVChargeParameterType: EVEnergyRequest
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub energy_amount: Option<Decimal>,
    /// Capacity of the electric vehicle battery (in Wh).
    /// Relates to: +
    /// *ISO 15118-2*: DC_EVChargeParameterType: EVEnergyCapacity
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_energy_capacity: Option<Decimal>,
    /// Maximum current (in A) supported by the electric vehicle. Includes cable capacity.
    /// Relates to: +
    /// *ISO 15118-2*: DC_EVChargeParameterType:EVMaximumCurrentLimit
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub ev_max_current: Decimal,
    /// Maximum power (in W) supported by the electric vehicle. Required for DC charging.
    /// Relates to: +
    /// *ISO 15118-2*: DC_EVChargeParameterType: EVMaximumPowerLimit
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_max_power: Option<Decimal>,
    /// Maximum voltage supported by the electric vehicle.
    /// Relates to: +
    /// *ISO 15118-2*: DC_EVChargeParameterType: EVMaximumVoltageLimit
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub ev_max_voltage: Decimal,
    /// Percentage of SoC at which the EV considers the battery fully charged. (possible values: 0 - 100)
    /// Relates to: +
    /// *ISO 15118-2*: DC_EVChargeParameterType: FullSOC
    #[serde(rename = "fullSoC")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub full_soc: Option<u8>,
    /// Energy available in the battery (in percent of the battery capacity)
    /// Relates to: +
    /// *ISO 15118-2*: DC_EVChargeParameterType: DC_EVStatus: EVRESSSOC
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub state_of_charge: Option<u8>,
}

static_assertions::assert_impl_all!(DCChargingParametersType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
