// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::der_curve::DERCurveType;
use crate::v2_1::enumerations::der_control::DERControlEnumType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct DERCurveGetType {
    pub curve: DERCurveType,
    pub curve_type: DERControlEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Id of DER curve
    #[validate(length(max = 36))]
    pub id: String,
    /// True if this is a default curve
    pub is_default: bool,
    /// True if this setting is superseded by a higher priority setting (i.e. lower value of _priority_)
    pub is_superseded: bool,
}

static_assertions::assert_impl_all!(DERCurveGetType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
