// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::der_control::DERControlEnumType;
use crate::v2_1::enumerations::islanding_detection::IslandingDetectionEnumType;
use rust_decimal::Decimal;
use validator::Validate;

/// *(2.1)* DERChargingParametersType is used in ChargingNeedsType during an ISO 15118-20 session for AC_BPT_DER to report the inverter settings related to DER control that were agreed between EVSE and EV.
///
/// Fields starting with "ev" contain values from the EV.
/// Other fields contain a value that is supported by both EV and EVSE.
///
/// DERChargingParametersType type is only relevant in case of an ISO 15118-20 AC_BPT_DER/AC_DER charging session.
///
/// NOTE: All these fields have values greater or equal to zero (i.e. are non-negative)
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct DERChargingParametersType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Maximum allowed duration of DC injection at level 1 charging. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVDurationLevel1DCInjection
    #[serde(rename = "evDurationLevel1DCInjection")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_duration_level1_dc_injection: Option<Decimal>,
    /// Maximum allowed duration of DC injection at level 2 charging. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVDurationLevel2DCInjection
    #[serde(rename = "evDurationLevel2DCInjection")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_duration_level2_dc_injection: Option<Decimal>,
    /// Hardware version of EV inverter. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVInverterHwVersion
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub ev_inverter_hw_version: Option<String>,
    /// Manufacturer of the EV inverter. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVInverterManufacturer
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub ev_inverter_manufacturer: Option<String>,
    /// Model name of the EV inverter. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVInverterModel
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub ev_inverter_model: Option<String>,
    /// Serial number of the EV inverter. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVInverterSerialNumber
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub ev_inverter_serial_number: Option<String>,
    /// Software version of EV inverter. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVInverterSwVersion
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub ev_inverter_sw_version: Option<String>,
    /// Type of islanding detection method. Only mandatory when islanding detection is required at the site, as set in the ISO 15118 Service Details configuration. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVIslandingDetectionMethod
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub ev_islanding_detection_method: Option<Vec<IslandingDetectionEnumType>>,
    /// Time after which EV will trip if an island has been detected. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVIslandingTripTime
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_islanding_trip_time: Option<Decimal>,
    /// Maximum injected DC current allowed at level 1 charging. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumLevel1DCInjection
    #[serde(rename = "evMaximumLevel1DCInjection")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_maximum_level1_dc_injection: Option<Decimal>,
    /// Maximum injected DC current allowed at level 2 charging. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumLevel2DCInjection
    #[serde(rename = "evMaximumLevel2DCInjection")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_maximum_level2_dc_injection: Option<Decimal>,
    /// Rated maximum injected active power by EV, at specified over-excited power factor (overExcitedPowerFactor). +
    /// It can also be defined as the rated maximum discharge power at the rated minimum injected reactive power value. This means that if the EV is providing reactive power support, and it is requested to discharge at max power (e.g. to satisfy an EMS request), the EV may override the request and discharge up to overExcitedMaximumDischargePower to meet the minimum reactive power requirements. +
    /// Corresponds to the WOvPF attribute in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVOverExcitedMaximumDischargePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_over_excited_max_discharge_power: Option<Decimal>,
    /// EV power factor when injecting (over excited) the minimum reactive power. +
    /// Corresponds to the OvPF attribute in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVOverExcitedPowerFactor
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_over_excited_power_factor: Option<Decimal>,
    ///  Measure of the susceptibility of the circuit to reactance, in Siemens (S). +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVReactiveSusceptance
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_reactive_susceptance: Option<Decimal>,
    /// Total energy value, in Wh, that EV is allowed to provide during the entire V2G session. The value is independent of the V2X Cycling area. Once this value reaches the value of 0, the EV may block any attempt to discharge in order to protect the battery health.
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVSessionTotalDischargeEnergyAvailable
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_session_total_discharge_energy_available: Option<Decimal>,
    /// DER control functions supported by EV. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType:DERControlFunctions (bitmap)
    #[serde(rename = "evSupportedDERControl")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub ev_supported_der_control: Option<Vec<DERControlEnumType>>,
    /// Rated maximum injected active power by EV supported at specified under-excited power factor (EVUnderExcitedPowerFactor). +
    /// It can also be defined as the rated maximum dischargePower at the rated minimum absorbed reactive power value.
    /// This means that if the EV is providing reactive power support, and it is requested to discharge at max power (e.g. to satisfy an EMS request), the EV may override the request and discharge up to underExcitedMaximumDischargePower to meet the minimum reactive power requirements. +
    /// This corresponds to the WUnPF attribute in the IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVUnderExcitedMaximumDischargePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_under_excited_max_discharge_power: Option<Decimal>,
    /// EV power factor when injecting (under excited) the minimum reactive power. +
    /// Corresponds to the OvPF attribute in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVUnderExcitedPowerFactor
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_under_excited_power_factor: Option<Decimal>,
    /// Rated maximum total apparent power, defined by min(EV, EVSE) in va.
    /// Corresponds to the VAMaxRtg in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumApparentPower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_apparent_power: Option<Decimal>,
    /// Rated maximum absorbed apparent power, defined by min(EV, EVSE) in va. +
    ///     This field represents the sum of all phases, unless values are provided for L2 and L3,
    ///     in which case this field represents phase L1. +
    ///     Corresponds to the ChaVAMaxRtg in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumChargeApparentPower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_apparent_power: Option<Decimal>,
    /// Rated maximum absorbed apparent power on phase L2, defined by min(EV, EVSE) in va.
    /// Corresponds to the ChaVAMaxRtg in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumChargeApparentPower_L2
    #[serde(rename = "maxChargeApparentPower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_apparent_power_l2: Option<Decimal>,
    /// Rated maximum absorbed apparent power on phase L3, defined by min(EV, EVSE) in va.
    /// Corresponds to the ChaVAMaxRtg in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumChargeApparentPower_L3
    #[serde(rename = "maxChargeApparentPower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_apparent_power_l3: Option<Decimal>,
    /// Rated maximum absorbed reactive power, defined by min(EV, EVSE), in vars. +
    ///     This field represents the sum of all phases, unless values are provided for L2 and L3,
    ///     in which case this field represents phase L1. +
    /// Corresponds to the AvarMax attribute in the IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumChargeReactivePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_reactive_power: Option<Decimal>,
    /// Rated maximum absorbed reactive power, defined by min(EV, EVSE), in vars on phase L2. +
    /// Corresponds to the AvarMax attribute in the IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumChargeReactivePower_L2
    #[serde(rename = "maxChargeReactivePower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_reactive_power_l2: Option<Decimal>,
    /// Rated maximum absorbed reactive power, defined by min(EV, EVSE), in vars on phase L3. +
    /// Corresponds to the AvarMax attribute in the IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumChargeReactivePower_L3
    #[serde(rename = "maxChargeReactivePower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_reactive_power_l3: Option<Decimal>,
    /// Rated maximum injected apparent power, defined by min(EV, EVSE) in va. +
    ///     This field represents the sum of all phases, unless values are provided for L2 and L3,
    ///     in which case this field represents phase L1. +
    ///     Corresponds to the DisVAMaxRtg in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumDischargeApparentPower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_apparent_power: Option<Decimal>,
    /// Rated maximum injected apparent power on phase L2, defined by min(EV, EVSE) in va. +
    ///     Corresponds to the DisVAMaxRtg in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumDischargeApparentPower_L2
    #[serde(rename = "maxDischargeApparentPower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_apparent_power_l2: Option<Decimal>,
    /// Rated maximum injected apparent power on phase L3, defined by min(EV, EVSE) in va. +
    ///     Corresponds to the DisVAMaxRtg in IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumDischargeApparentPower_L3
    #[serde(rename = "maxDischargeApparentPower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_apparent_power_l3: Option<Decimal>,
    /// Rated maximum injected reactive power, defined by min(EV, EVSE), in vars. +
    ///     This field represents the sum of all phases, unless values are provided for L2 and L3,
    ///     in which case this field represents phase L1. +
    /// Corresponds to the IvarMax attribute in the IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumDischargeReactivePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_reactive_power: Option<Decimal>,
    /// Rated maximum injected reactive power, defined by min(EV, EVSE), in vars on phase L2. +
    /// Corresponds to the IvarMax attribute in the IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumDischargeReactivePower_L2
    #[serde(rename = "maxDischargeReactivePower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_reactive_power_l2: Option<Decimal>,
    /// Rated maximum injected reactive power, defined by min(EV, EVSE), in vars on phase L3. +
    /// Corresponds to the IvarMax attribute in the IEC 61850. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumDischargeReactivePower_L3
    #[serde(rename = "maxDischargeReactivePower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_reactive_power_l3: Option<Decimal>,
    /// Maximum AC rms voltage, as defined by min(EV, EVSE)  to operate with. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMaximumNominalVoltage
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_nominal_voltage: Option<Decimal>,
    /// Rated minimum absorbed reactive power, defined by max(EV, EVSE), in vars. +
    ///     This field represents the sum of all phases, unless values are provided for L2 and L3,
    ///     in which case this field represents phase L1. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMinimumChargeReactivePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charge_reactive_power: Option<Decimal>,
    /// Rated minimum absorbed reactive power, defined by max(EV, EVSE), in vars on phase L2. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMinimumChargeReactivePower_L2
    #[serde(rename = "minChargeReactivePower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charge_reactive_power_l2: Option<Decimal>,
    /// Rated minimum absorbed reactive power, defined by max(EV, EVSE), in vars on phase L3. +
    ///     *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMinimumChargeReactivePower_L3
    #[serde(rename = "minChargeReactivePower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charge_reactive_power_l3: Option<Decimal>,
    /// Rated minimum injected reactive power, defined by max(EV, EVSE), in vars. +
    ///     This field represents the sum of all phases, unless values are provided for L2 and L3,
    ///     in which case this field represents phase L1. +
    ///         *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMinimumDischargeReactivePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_discharge_reactive_power: Option<Decimal>,
    /// Rated minimum injected reactive power, defined by max(EV, EVSE), in var on phase L2. +
    ///         *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMinimumDischargeReactivePower_L2
    #[serde(rename = "minDischargeReactivePower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_discharge_reactive_power_l2: Option<Decimal>,
    /// Rated minimum injected reactive power, defined by max(EV, EVSE), in var on phase L3. +
    ///         *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMinimumDischargeReactivePower_L3
    #[serde(rename = "minDischargeReactivePower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_discharge_reactive_power_l3: Option<Decimal>,
    /// Minimum AC rms voltage, as defined by max(EV, EVSE)  to operate with. +
    ///        *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVMinimumNominalVoltage
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_nominal_voltage: Option<Decimal>,
    /// Line voltage supported by EVSE and EV.
    ///         *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVNominalVoltage
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub nominal_voltage: Option<Decimal>,
    /// The nominal AC voltage (rms) offset between the Charging Station's electrical connection point and the utility’s point of common coupling. +
    ///         *ISO 15118-20*: DER_BPT_AC_CPDReqEnergyTransferModeType: EVNominalVoltageOffset
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub nominal_voltage_offset: Option<Decimal>,
}

static_assertions::assert_impl_all!(DERChargingParametersType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
