// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct DERCurvePointsType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The data value of the X-axis (independent) variable, depending on the curve type.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub x: Decimal,
    /// The data value of the Y-axis (dependent) variable, depending on the  &lt;&lt;cmn_derunitenumtype&gt;&gt; of the curve. If _y_ is power factor, then a positive value means DER is absorbing reactive power (under-excited), a negative value when DER is injecting reactive power (over-excited).
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub y: Decimal,
}

static_assertions::assert_impl_all!(DERCurvePointsType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
