// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::der_curve_points::DERCurvePointsType;
use crate::v2_1::datatypes::hysteresis::HysteresisType;
use crate::v2_1::datatypes::reactive_power_params::ReactivePowerParamsType;
use crate::v2_1::datatypes::voltage_params::VoltageParamsType;
use crate::v2_1::enumerations::der_unit::DERUnitEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct DERCurveType {
    #[validate(length(min = 1, max = 10))]
    pub curve_data: Vec<DERCurvePointsType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Duration in seconds that this curve will be active. Only absent when _default_ is true.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub duration: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hysteresis: Option<HysteresisType>,
    /// Priority of curve (0=highest)
    #[validate(range(min = 0))]
    pub priority: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reactive_power_params: Option<ReactivePowerParamsType>,
    /// Open loop response time, the time to ramp up to 90% of the new target in response to the change in voltage, in seconds. A value of 0 is used to mean no limit. When not present, the device should follow its default behavior.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub response_time: Option<Decimal>,
    /// Point in time when this curve will become activated. Only absent when _default_ is true.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub start_time: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub voltage_params: Option<VoltageParamsType>,
    pub y_unit: DERUnitEnumType,
}

static_assertions::assert_impl_all!(DERCurveType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
