// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct EnterServiceType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Enter service delay
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub delay: Option<Decimal>,
    /// Enter service frequency high
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub high_freq: Decimal,
    /// Enter service voltage high
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub high_voltage: Decimal,
    /// Enter service frequency low
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub low_freq: Decimal,
    /// Enter service voltage low
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub low_voltage: Decimal,
    /// Priority of setting (0=highest)
    #[validate(range(min = 0))]
    pub priority: u32,
    /// Enter service ramp rate in seconds
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ramp_rate: Option<Decimal>,
    /// Enter service randomized delay
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub random_delay: Option<Decimal>,
}

static_assertions::assert_impl_all!(EnterServiceType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
