// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::ev_absolute_price_schedule_entry::EVAbsolutePriceScheduleEntryType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// *(2.1)* Price schedule of EV energy offer.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct EVAbsolutePriceScheduleType {
    /// Currency code according to ISO 4217.
    #[validate(length(max = 3))]
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[validate(length(min = 1, max = 1024))]
    pub ev_absolute_price_schedule_entries: Vec<EVAbsolutePriceScheduleEntryType>,
    /// ISO 15118-20 URN of price algorithm: Power, PeakPower, StackedEnergy.
    #[validate(length(max = 2000))]
    pub price_algorithm: String,
    /// Starting point in time of the EVEnergyOffer.
    #[serde(with = "datetime_rfc3339")]
    pub time_anchor: DateTime<Utc>,
}

static_assertions::assert_impl_all!(EVAbsolutePriceScheduleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
