// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::ev_price_rule::EVPriceRuleType;
use validator::Validate;

/// *(2.1)* An entry in price schedule over time for which EV is willing to discharge.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct EVAbsolutePriceScheduleEntryType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The amount of seconds of this entry.
    pub duration: i32,
    #[validate(length(min = 1, max = 8))]
    pub ev_price_rule: Vec<EVPriceRuleType>,
}

static_assertions::assert_impl_all!(EVAbsolutePriceScheduleEntryType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
