// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::ev_absolute_price_schedule::EVAbsolutePriceScheduleType;
use crate::v2_1::datatypes::ev_power_schedule::EVPowerScheduleType;

/// *(2.1)* A schedule of the energy amount over time that EV is willing to discharge. A negative value indicates the willingness to discharge under specific conditions, a positive value indicates that the EV currently is not able to offer energy to discharge.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct EVEnergyOfferType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ev_absolute_price_schedule: Option<EVAbsolutePriceScheduleType>,
    pub ev_power_schedule: EVPowerScheduleType,
}

static_assertions::assert_impl_all!(EVEnergyOfferType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
