// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;

/// *(2.1)* An entry in price schedule over time for which EV is willing to discharge.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct EVPriceRuleType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Cost per kWh.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub energy_fee: Decimal,
    /// The EnergyFee applies between this value and the value of the PowerRangeStart of the subsequent EVPriceRule. If the power is below this value, the EnergyFee of the previous EVPriceRule applies. Negative values are used for discharging.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub power_range_start: Decimal,
}

static_assertions::assert_impl_all!(EVPriceRuleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
