// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::component::ComponentType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::variable::VariableType;
use crate::v2_1::enumerations::event_notification::EventNotificationEnumType;
use crate::v2_1::enumerations::event_trigger::EventTriggerEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// Class to report an event notification for a component-variable.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct EventDataType {
    /// Actual value (_attributeType_ Actual) of the variable.
    ///
    /// The Configuration Variable &lt;&lt;configkey-reporting-value-size,ReportingValueSize&gt;&gt; can be used to limit GetVariableResult.attributeValue, VariableAttribute.value and EventData.actualValue. The max size of these values will always remain equal.
    #[validate(length(max = 2500))]
    pub actual_value: String,
    /// Refers to the Id of an event that is considered to be the cause for this event.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub cause: Option<u32>,
    /// _Cleared_ is set to true to report the clearing of a monitored situation, i.e. a 'return to normal'.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cleared: Option<bool>,
    pub component: ComponentType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Identifies the event. This field can be referred to as a cause by other events.
    #[validate(range(min = 0))]
    pub event_id: u32,
    pub event_notification_type: EventNotificationEnumType,
    /// *(2.1)* Severity associated with the monitor in _variableMonitoringId_ or with the hardwired notification.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub severity: Option<u32>,
    /// Technical (error) code as reported by component.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub tech_code: Option<String>,
    /// Technical detail information as reported by component.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 500))]
    pub tech_info: Option<String>,
    /// Timestamp of the moment the report was generated.
    #[serde(with = "datetime_rfc3339")]
    pub timestamp: DateTime<Utc>,
    /// If an event notification is linked to a specific transaction, this field can be used to specify its transactionId.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 36))]
    pub transaction_id: Option<String>,
    pub trigger: EventTriggerEnumType,
    pub variable: VariableType,
    /// Identifies the VariableMonitoring which triggered the event.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub variable_monitoring_id: Option<u32>,
}

static_assertions::assert_impl_all!(EventDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
