// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

/// Electric Vehicle Supply Equipment
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct EVSEType {
    /// An id to designate a specific connector (on an EVSE) by connector index number.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub connector_id: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// EVSE Identifier. This contains a number (&gt; 0) designating an EVSE of the Charging Station.
    #[validate(range(min = 0))]
    pub id: u32,
}

static_assertions::assert_impl_all!(EVSEType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
