// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::fixed_pf::FixedPFType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct FixedPFGetType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(rename = "fixedPF")]
    pub fixed_pf: FixedPFType,
    /// Id of setting.
    #[validate(length(max = 36))]
    pub id: String,
    /// True if setting is a default control.
    pub is_default: bool,
    /// True if this setting is superseded by a lower priority setting.
    pub is_superseded: bool,
}

static_assertions::assert_impl_all!(FixedPFGetType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
