// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct FixedPFType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Power factor, cos(phi), as value between 0..1.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub displacement: Decimal,
    /// Duration in seconds that this setting is active.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub duration: Option<Decimal>,
    /// True when absorbing reactive power (under-excited), false when injecting reactive power (over-excited).
    pub excitation: bool,
    /// Priority of setting (0=highest)
    #[validate(range(min = 0))]
    pub priority: u32,
    /// Time when this setting becomes active
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub start_time: Option<DateTime<Utc>>,
}

static_assertions::assert_impl_all!(FixedPFType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
