// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::der_unit::DERUnitEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct FixedVarType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Duration in seconds that this setting is active.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub duration: Option<Decimal>,
    /// Priority of setting (0=highest)
    #[validate(range(min = 0))]
    pub priority: u32,
    /// The value specifies a target var output interpreted as a signed percentage (-100 to 100).
    ///     A negative value refers to charging, whereas a positive one refers to discharging.
    ///     The value type is determined by the unit field.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub setpoint: Decimal,
    /// Time when this setting becomes active.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub start_time: Option<DateTime<Utc>>,
    pub unit: DERUnitEnumType,
}

static_assertions::assert_impl_all!(FixedVarType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
