// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct FreqDroopType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Duration in seconds that this setting is active
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub duration: Option<Decimal>,
    /// Over-frequency droop per unit, oFDroop
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub over_droop: Decimal,
    /// Over-frequency start of droop
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub over_freq: Decimal,
    /// Priority of setting (0=highest)
    #[validate(range(min = 0))]
    pub priority: u32,
    /// Open loop response time in seconds
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub response_time: Decimal,
    /// Time when this setting becomes active
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub start_time: Option<DateTime<Utc>>,
    /// Under-frequency droop per unit, uFDroop
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub under_droop: Decimal,
    /// Under-frequency start of droop
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub under_freq: Decimal,
}

static_assertions::assert_impl_all!(FreqDroopType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
