// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct GradientType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Default ramp rate in seconds (0 if not applicable)
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub gradient: Decimal,
    /// Id of setting
    #[validate(range(min = 0))]
    pub priority: u32,
    /// Soft-start ramp rate in seconds (0 if not applicable)
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub soft_gradient: Decimal,
}

static_assertions::assert_impl_all!(GradientType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
