// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct HysteresisType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Delay in seconds, once grid parameter within HysteresisLow and HysteresisHigh, for the EV to return to normal operation after a grid event.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub hysteresis_delay: Option<Decimal>,
    /// Set default rate of change (ramp rate %/s) for the EV to return to normal operation after a grid event
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub hysteresis_gradient: Option<Decimal>,
    /// High value for return to normal operation after a grid event, in absolute value. This value adopts the same unit as defined by yUnit
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub hysteresis_high: Option<Decimal>,
    /// Low value for return to normal operation after a grid event, in absolute value. This value adopts the same unit as defined by yUnit
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub hysteresis_low: Option<Decimal>,
}

static_assertions::assert_impl_all!(HysteresisType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
