// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::additional_info::AdditionalInfoType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

/// Contains a case insensitive identifier to use for the authorization and the type of authorization to support multiple forms of identifiers.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct IdTokenType {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub additional_info: Option<Vec<AdditionalInfoType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// *(2.1)* IdToken is case insensitive. Might hold the hidden id of an RFID tag, but can for example also contain a UUID.
    #[validate(length(max = 255))]
    pub id_token: String,
    /// *(2.1)* Enumeration of possible idToken types. Values defined in Appendix as IdTokenEnumStringType.
    #[serde(rename = "type")]
    #[validate(length(max = 20))]
    pub kind: String,
}

static_assertions::assert_impl_all!(IdTokenType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
