// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::der_curve::DERCurveType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use rust_decimal::Decimal;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct LimitMaxDischargeType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Duration in seconds that this setting is active
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub duration: Option<Decimal>,
    /// Only for PowerMonitoring. +
    ///     The value specifies a percentage (0 to 100) of the rated maximum discharge power of EV.
    ///     The PowerMonitoring curve becomes active when power exceeds this percentage.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub pct_max_discharge_power: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub power_monitoring_must_trip: Option<DERCurveType>,
    /// Priority of setting (0=highest)
    #[validate(range(min = 0))]
    pub priority: u32,
    /// Time when this setting becomes active
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub start_time: Option<DateTime<Utc>>,
}

static_assertions::assert_impl_all!(LimitMaxDischargeType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
