// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::component::ComponentType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::variable::VariableType;
use crate::v2_1::datatypes::variable_monitoring::VariableMonitoringType;
use validator::Validate;

/// Class to hold parameters of SetVariableMonitoring request.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct MonitoringDataType {
    pub component: ComponentType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub variable: VariableType,
    #[validate(length(min = 1))]
    pub variable_monitoring: Vec<VariableMonitoringType>,
}

static_assertions::assert_impl_all!(MonitoringDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
