// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::apn::APNType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::vpn::VPNType;
use crate::v2_1::enumerations::ocpp_interface::OCPPInterfaceEnumType;
use crate::v2_1::enumerations::ocpp_transport::OCPPTransportEnumType;
use crate::v2_1::enumerations::ocpp_version::OCPPVersionEnumType;
use validator::Validate;

/// The NetworkConnectionProfile defines the functional and technical parameters of a communication link.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct NetworkConnectionProfileType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub apn: Option<APNType>,
    /// *(2.1)* BasicAuthPassword to use for security profile 1 or 2.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 64))]
    pub basic_auth_password: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// *(2.1)* Charging Station identity to be used as the basic authentication username.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 48))]
    pub identity: Option<String>,
    /// Duration in seconds before a message send by the Charging Station via this network connection times-out.
    /// The best setting depends on the underlying network and response times of the CSMS.
    /// If you are looking for a some guideline: use 30 seconds as a starting point.
    pub message_timeout: i32,
    /// URL of the CSMS(s) that this Charging Station communicates with, without the Charging Station identity part. +
    /// The SecurityCtrlr.Identity field is appended to _ocppCsmsUrl_ to provide the full websocket URL.
    #[validate(length(max = 2000))]
    pub ocpp_csms_url: String,
    pub ocpp_interface: OCPPInterfaceEnumType,
    pub ocpp_transport: OCPPTransportEnumType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ocpp_version: Option<OCPPVersionEnumType>,
    /// This field specifies the security profile used when connecting to the CSMS with this NetworkConnectionProfile.
    #[validate(range(min = 0))]
    pub security_profile: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vpn: Option<VPNType>,
}

static_assertions::assert_impl_all!(NetworkConnectionProfileType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
