// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::hash_algorithm::HashAlgorithmEnumType;
use validator::Validate;

/// Information about a certificate for an OCSP check.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct OCSPRequestDataType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub hash_algorithm: HashAlgorithmEnumType,
    /// The hash of the DER encoded public key:
    /// the value (excluding tag and length) of the subject
    /// public key field in the issuer’s certificate.
    #[validate(length(max = 128))]
    pub issuer_key_hash: String,
    /// The hash of the issuer’s distinguished
    /// name (DN), that must be calculated over the DER
    /// encoding of the issuer’s name field in the certificate
    /// being checked.
    #[validate(length(max = 128))]
    pub issuer_name_hash: String,
    /// This contains the responder URL (Case insensitive).
    #[serde(rename = "responderURL")]
    #[validate(length(max = 2000))]
    pub responder_url: String,
    /// The string representation of the
    /// hexadecimal value of the serial number without the
    /// prefix "0x" and without leading zeroes.
    #[validate(length(max = 40))]
    pub serial_number: String,
}

static_assertions::assert_impl_all!(OCSPRequestDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
