// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::rational_number::RationalNumberType;
use validator::Validate;

/// Part of ISO 15118-20 price schedule.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct OverstayRuleType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub overstay_fee: RationalNumberType,
    /// Time till overstay will be reapplied
    pub overstay_fee_period: i32,
    /// Human readable string to identify the overstay rule.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 32))]
    pub overstay_rule_description: Option<String>,
    /// Time in seconds after trigger of the parent Overstay Rules for this particular fee to apply.
    pub start_time: i32,
}

static_assertions::assert_impl_all!(OverstayRuleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
