// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::overstay_rule::OverstayRuleType;
use crate::v2_1::datatypes::rational_number::RationalNumberType;
use validator::Validate;

/// Part of ISO 15118-20 price schedule.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct OverstayRuleListType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overstay_power_threshold: Option<RationalNumberType>,
    #[validate(length(min = 1, max = 5))]
    pub overstay_rule: Vec<OverstayRuleType>,
    /// Time till overstay is applied in seconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overstay_time_threshold: Option<i32>,
}

static_assertions::assert_impl_all!(OverstayRuleListType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
