// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::tax_rate::TaxRateType;
use rust_decimal::Decimal;
use validator::Validate;

/// Price with and without tax. At least one of _exclTax_, _inclTax_ must be present.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct PriceType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Price/cost excluding tax. Can be absent if _inclTax_ is present.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub excl_tax: Option<Decimal>,
    /// Price/cost including tax. Can be absent if _exclTax_ is present.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub incl_tax: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 5))]
    pub tax_rates: Option<Vec<TaxRateType>>,
}

static_assertions::assert_impl_all!(PriceType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
