// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::rational_number::RationalNumberType;
use validator::Validate;

/// Part of ISO 15118-20 price schedule.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct PriceRuleType {
    /// Number of grams of CO2 per kWh.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub carbon_dioxide_emission: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    pub energy_fee: RationalNumberType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parking_fee: Option<RationalNumberType>,
    /// The duration of the parking fee period (in seconds).
    /// When the time enters into a ParkingFeePeriod, the ParkingFee will apply to the session. .
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parking_fee_period: Option<i32>,
    pub power_range_start: RationalNumberType,
    /// Percentage of the power that is created by renewable resources.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub renewable_generation_percentage: Option<u8>,
}

static_assertions::assert_impl_all!(PriceRuleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
