// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::price_rule::PriceRuleType;
use validator::Validate;

/// Part of ISO 15118-20 price schedule.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct PriceRuleStackType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Duration of the stack of price rules.  he amount of seconds that define the duration of the given PriceRule(s).
    pub duration: i32,
    #[validate(length(min = 1, max = 8))]
    pub price_rule: Vec<PriceRuleType>,
}

static_assertions::assert_impl_all!(PriceRuleStackType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
