// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::price_level_schedule_entry::PriceLevelScheduleEntryType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// The PriceLevelScheduleType is modeled after the same type that is defined in ISO 15118-20, such that if it is supplied by an EMSP as a signed EXI message, the conversion from EXI to JSON (in OCPP) and back to EXI (for ISO 15118-20) does not change the digest and therefore does not invalidate the signature.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct PriceLevelScheduleType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Defines the overall number of distinct price level elements used across all PriceLevelSchedules.
    #[validate(range(min = 0))]
    pub number_of_price_levels: u32,
    #[validate(length(min = 1, max = 100))]
    pub price_level_schedule_entries: Vec<PriceLevelScheduleEntryType>,
    /// Description of the price schedule.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 32))]
    pub price_schedule_description: Option<String>,
    /// Unique ID of this price schedule.
    #[validate(range(min = 0))]
    pub price_schedule_id: u32,
    /// Starting point of this price schedule.
    #[serde(with = "datetime_rfc3339")]
    pub time_anchor: DateTime<Utc>,
}

static_assertions::assert_impl_all!(PriceLevelScheduleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
