// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;

/// Part of ISO 15118-20 price schedule.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct RationalNumberType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// The exponent to base 10 (dec)
    pub exponent: i32,
    /// Value which shall be multiplied.
    pub value: i32,
}

static_assertions::assert_impl_all!(RationalNumberType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
