// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct ReactivePowerParamsType {
    /// Only for VoltVar: Enable/disable autonomous VRef adjustment
    #[serde(skip_serializing_if = "Option::is_none")]
    pub autonomous_v_ref_enable: Option<bool>,
    /// Only for VoltVar: Adjustment range for VRef time constant
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub autonomous_v_ref_time_constant: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Only for VoltVar curve: The nominal ac voltage (rms) adjustment to the voltage curve points for Volt-Var curves (percentage).
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub v_ref: Option<Decimal>,
}

static_assertions::assert_impl_all!(ReactivePowerParamsType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
