// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::consumption_cost::ConsumptionCostType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::relative_time_interval::RelativeTimeIntervalType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct SalesTariffEntryType {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 3))]
    pub consumption_cost: Option<Vec<ConsumptionCostType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Defines the price level of this SalesTariffEntry (referring to NumEPriceLevels). Small values for the EPriceLevel represent a cheaper TariffEntry. Large values for the EPriceLevel represent a more expensive TariffEntry.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub e_price_level: Option<u32>,
    pub relative_time_interval: RelativeTimeIntervalType,
}

static_assertions::assert_impl_all!(SalesTariffEntryType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
