// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::signed_meter_value::SignedMeterValueType;
use crate::v2_1::datatypes::unit_of_measure::UnitOfMeasureType;
use crate::v2_1::enumerations::location::LocationEnumType;
use crate::v2_1::enumerations::measurand::MeasurandEnumType;
use crate::v2_1::enumerations::phase::PhaseEnumType;
use crate::v2_1::enumerations::reading_context::ReadingContextEnumType;
use rust_decimal::Decimal;

/// Single sampled value in MeterValues. Each value can be accompanied by optional fields.
///
/// To save on mobile data usage, default values of all of the optional fields are such that. The value without any additional fields will be interpreted, as a register reading of active import energy in Wh (Watt-hour) units.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct SampledValueType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<ReadingContextEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<LocationEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub measurand: Option<MeasurandEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phase: Option<PhaseEnumType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signed_meter_value: Option<SignedMeterValueType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_of_measure: Option<UnitOfMeasureType>,
    /// Indicates the measured value.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub value: Decimal,
}

static_assertions::assert_impl_all!(SampledValueType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
