// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::component::ComponentType;
use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::periodic_event_stream_params::PeriodicEventStreamParamsType;
use crate::v2_1::datatypes::variable::VariableType;
use crate::v2_1::enumerations::monitor::MonitorEnumType;
use rust_decimal::Decimal;
use validator::Validate;

/// Class to hold parameters of SetVariableMonitoring request.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct SetMonitoringDataType {
    pub component: ComponentType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// An id SHALL only be given to replace an existing monitor. The Charging Station handles the generation of id's for new monitors.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub id: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub periodic_event_stream: Option<PeriodicEventStreamParamsType>,
    /// The severity that will be assigned to an event that is triggered by this monitor. The severity range is 0-9, with 0 as the highest and 9 as the lowest severity level.
    ///
    /// The severity levels have the following meaning: +
    /// *0-Danger* +
    /// Indicates lives are potentially in danger. Urgent attention is needed and action should be taken immediately. +
    /// *1-Hardware Failure* +
    /// Indicates that the Charging Station is unable to continue regular operations due to Hardware issues. Action is required. +
    /// *2-System Failure* +
    /// Indicates that the Charging Station is unable to continue regular operations due to software or minor hardware issues. Action is required. +
    /// *3-Critical* +
    /// Indicates a critical error. Action is required. +
    /// *4-Error* +
    /// Indicates a non-urgent error. Action is required. +
    /// *5-Alert* +
    /// Indicates an alert event. Default severity for any type of monitoring event.  +
    /// *6-Warning* +
    /// Indicates a warning event. Action may be required. +
    /// *7-Notice* +
    /// Indicates an unusual event. No immediate action is required. +
    /// *8-Informational* +
    /// Indicates a regular operational event. May be used for reporting, measuring throughput, etc. No action is required. +
    /// *9-Debug* +
    /// Indicates information useful to developers for debugging, not useful during operations.
    #[validate(range(min = 0))]
    pub severity: u32,
    /// Monitor only active when a transaction is ongoing on a component relevant to this transaction. Default = false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction: Option<bool>,
    #[serde(rename = "type")]
    pub kind: MonitorEnumType,
    /// Value for threshold or delta monitoring.
    /// For Periodic or PeriodicClockAligned this is the interval in seconds.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub value: Decimal,
    pub variable: VariableType,
}

static_assertions::assert_impl_all!(SetMonitoringDataType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
