// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use validator::Validate;

/// Element providing more information about the status.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct StatusInfoType {
    /// Additional text to provide detailed information.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 1024))]
    pub additional_info: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// A predefined code for the reason why the status is returned in this response. The string is case-insensitive.
    #[validate(length(max = 20))]
    pub reason_code: String,
}

static_assertions::assert_impl_all!(StatusInfoType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
