// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::tariff_fixed_price::TariffFixedPriceType;
use crate::v2_1::datatypes::tax_rate::TaxRateType;
use validator::Validate;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TariffFixedType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[validate(length(min = 1))]
    pub prices: Vec<TariffFixedPriceType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 5))]
    pub tax_rates: Option<Vec<TaxRateType>>,
}

static_assertions::assert_impl_all!(TariffFixedType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
