// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::tariff_conditions_fixed::TariffConditionsFixedType;
use rust_decimal::Decimal;

/// Tariff with optional conditions for a fixed price.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct TariffFixedPriceType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<TariffConditionsFixedType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Fixed price  for this element e.g. a start fee.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub price_fixed: Decimal,
}

static_assertions::assert_impl_all!(TariffFixedPriceType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
