// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::day_of_week::DayOfWeekEnumType;
use crate::v2_1::enumerations::evse_kind::EvseKindEnumType;
use rust_decimal::Decimal;
use validator::Validate;

/// These conditions describe if and when a TariffEnergyType or TariffTimeType applies during a transaction.
///
/// When more than one restriction is set, they are to be treated as a logical AND. All need to be valid before this price is active.
///
/// For reverse energy flow (discharging) negative values of energy, power and current are used.
///
/// NOTE: _minXXX_ (where XXX = Kwh/A/Kw) must be read as "closest to zero", and _maxXXX_ as "furthest from zero". For example, a *charging* power range from 10 kW to 50 kWh is given by _minPower_ = 10000 and _maxPower_ = 50000, and a *discharging* power range from -10 kW to -50 kW is given by _minPower_ = -10 and _maxPower_ = -50.
///
/// NOTE: _startTimeOfDay_ and _endTimeOfDay_ are in local time, because it is the time in the tariff as it is shown to the EV driver at the Charging Station.
/// A Charging Station will convert this to the internal time zone that it uses (which is recommended to be UTC, see section Generic chapter 3.1) when performing cost calculation.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TariffConditionsType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Day(s) of the week this is tariff applies.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 7))]
    pub day_of_week: Option<Vec<DayOfWeekEnumType>>,
    /// End time of day in local time. Same syntax as _startTimeOfDay_. +
    ///     If end time &lt; start time then the period wraps around to the next day. +
    ///     To stop at end of the day use: 00:00.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_time_of_day: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evse_kind: Option<EvseKindEnumType>,
    /// Maximum duration in seconds the charging MUST last (exclusive).
    ///       When the duration of a charging is shorter than the defined value, this price is or becomes active.
    ///       After that moment, this price is no longer active.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_charging_time: Option<i32>,
    /// Sum of the maximum current (in Amperes) over all phases, for example 20 A.
    ///       When the EV is charging with less than the defined amount of current, this price becomes/is active. If the charging current is or becomes higher, this price is not or no longer valid and becomes inactive.
    ///       This is NOT about the maximum current over the entire transaction.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_current: Option<Decimal>,
    /// Maximum consumed energy in Wh, for example 50000 Wh.
    ///     Valid until this amount of energy (exclusive) being used.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_energy: Option<Decimal>,
    /// Maximum duration in seconds the idle period (i.e. not charging) MUST last (exclusive).
    ///       When the duration of idle time is shorter than the defined value, this price is or becomes active.
    ///       After that moment, this price is no longer active.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_idle_time: Option<i32>,
    /// Maximum power in W, for example 20000 W.
    ///       When the EV is charging with less than the defined amount of power, this price becomes/is active.
    ///       If the charging power is or becomes higher, this price is not or no longer valid and becomes inactive.
    ///       This is NOT about the maximum power over the entire transaction.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_power: Option<Decimal>,
    /// Maximum duration in seconds the transaction (charging &amp; idle) MUST last (exclusive).
    ///       When the duration of a transaction is shorter than the defined value, this price is or becomes active.
    ///       After that moment, this price is no longer active.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_time: Option<i32>,
    /// Minimum duration in seconds the charging MUST last (inclusive).
    ///       When the duration of a charging is longer than the defined value, this price is or becomes active.
    ///       Before that moment, this price is not yet active.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_charging_time: Option<i32>,
    /// Sum of the minimum current (in Amperes) over all phases, for example 5 A.
    ///     When the EV is charging with more than, or equal to, the defined amount of current, this price is/becomes active. If the charging current is or becomes lower, this price is not or no longer valid and becomes inactive. +
    ///     This is NOT about the minimum current over the entire transaction.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_current: Option<Decimal>,
    /// Minimum consumed energy in Wh, for example 20000 Wh.
    ///     Valid from this amount of energy (inclusive) being used.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_energy: Option<Decimal>,
    /// Minimum duration in seconds the idle period (i.e. not charging) MUST last (inclusive).
    ///       When the duration of the idle time is longer than the defined value, this price is or becomes active.
    ///       Before that moment, this price is not yet active.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_idle_time: Option<i32>,
    /// Minimum power in W, for example 5000 W.
    ///       When the EV is charging with more than, or equal to, the defined amount of power, this price is/becomes active.
    ///       If the charging power is or becomes lower, this price is not or no longer valid and becomes inactive.
    ///       This is NOT about the minimum power over the entire transaction.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_power: Option<Decimal>,
    /// Minimum duration in seconds the transaction (charging &amp; idle) MUST last (inclusive).
    ///       When the duration of a transaction is longer than the defined value, this price is or becomes active.
    ///       Before that moment, this price is not yet active.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_time: Option<i32>,
    /// Start time of day in local time. +
    /// Format as per RFC 3339: time-hour ":" time-minute  +
    /// Must be in 24h format with leading zeros. Hour/Minute separator: ":"
    /// Regex: ([0-1][0-9]\|2[0-3]):[0-5][0-9]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_time_of_day: Option<String>,
    /// Start date in local time, for example: 2015-12-24.
    /// Valid from this day (inclusive). +
    /// Format as per RFC 3339: full-date  +
    ///
    /// Regex: ([12][0-9]{3})-(0[1-9]\|1[0-2])-(0[1-9]\|[12][0-9]\|3[01])
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_from_date: Option<String>,
    /// End date in local time, for example: 2015-12-27.
    ///     Valid until this day (exclusive). Same syntax as _validFromDate_.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub valid_to_date: Option<String>,
}

static_assertions::assert_impl_all!(TariffConditionsType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
