// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::message_content::MessageContentType;
use crate::v2_1::datatypes::price::PriceType;
use crate::v2_1::datatypes::tariff_energy::TariffEnergyType;
use crate::v2_1::datatypes::tariff_fixed::TariffFixedType;
use crate::v2_1::datatypes::tariff_time::TariffTimeType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// A tariff is described by fields with prices for:
/// energy,
/// charging time,
/// idle time,
/// fixed fee,
/// reservation time,
/// reservation fixed fee. +
/// Each of these fields may have (optional) conditions that specify when a price is applicable. +
/// The _description_ contains a human-readable explanation of the tariff to be shown to the user. +
/// The other fields are parameters that define the tariff. These are used by the charging station to calculate the price.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TariffType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub charging_time: Option<TariffTimeType>,
    /// Currency code according to ISO 4217
    #[validate(length(max = 3))]
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1, max = 10))]
    pub description: Option<Vec<MessageContentType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub energy: Option<TariffEnergyType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_fee: Option<TariffFixedType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idle_time: Option<TariffTimeType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_cost: Option<PriceType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_cost: Option<PriceType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reservation_fixed: Option<TariffFixedType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reservation_time: Option<TariffTimeType>,
    /// Unique id of tariff
    #[validate(length(max = 60))]
    pub tariff_id: String,
    /// Time when this tariff becomes active. When absent, it is immediately active.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub valid_from: Option<DateTime<Utc>>,
}

static_assertions::assert_impl_all!(TariffType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
