// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::tariff_kind::TariffKindEnumType;
use crate::v2_1::helpers::datetime_rfc3339;
use chrono::DateTime;
use chrono::Utc;
use validator::Validate;

/// Shows assignment of tariffs to EVSE or IdToken.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TariffAssignmentType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub evse_ids: Option<Vec<u32>>,
    /// IdTokens related to tariff
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(min = 1))]
    pub id_tokens: Option<Vec<String>>,
    /// Tariff id.
    #[validate(length(max = 60))]
    pub tariff_id: String,
    pub tariff_kind: TariffKindEnumType,
    /// Date/time when this tariff become active.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "datetime_rfc3339::option"
    )]
    pub valid_from: Option<DateTime<Utc>>,
}

static_assertions::assert_impl_all!(TariffAssignmentType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
