// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::tariff_conditions::TariffConditionsType;
use rust_decimal::Decimal;

/// Tariff with optional conditions for a time duration price.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct TariffTimePriceType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<TariffConditionsType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Price per minute (excl. tax) for this element.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub price_minute: Decimal,
}

static_assertions::assert_impl_all!(TariffTimePriceType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
