// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::datatypes::rational_number::RationalNumberType;
use validator::Validate;

/// Part of ISO 15118-20 price schedule.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TaxRuleType {
    /// Indicates whether this tax applies to Energy Fees.
    pub applies_to_energy_fee: bool,
    /// Indicates whether this tax applies to Minimum/Maximum Cost.
    pub applies_to_minimum_maximum_cost: bool,
    /// Indicates whether this tax applies to Overstay Fees.
    pub applies_to_overstay_fee: bool,
    /// Indicates whether this tax applies to Parking Fees.
    pub applies_to_parking_fee: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Indicates whether the tax is included in any price or not.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_included_in_price: Option<bool>,
    pub tax_rate: RationalNumberType,
    /// Id for the tax rule.
    #[serde(rename = "taxRuleID")]
    #[validate(range(min = 0))]
    pub tax_rule_id: u32,
    /// Human readable string to identify the tax rule.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 100))]
    pub tax_rule_name: Option<String>,
}

static_assertions::assert_impl_all!(TaxRuleType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
