// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;
use validator::Validate;

/// Tax percentage
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TaxRateType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Stack level for this type of tax. Default value, when absent, is 0. +
    /// _stack_ = 0: tax on net price; +
    /// _stack_ = 1: tax added on top of _stack_ 0; +
    /// _stack_ = 2: tax added on top of _stack_ 1, etc.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0))]
    pub stack: Option<u32>,
    /// Tax percentage
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub tax: Decimal,
    /// Type of this tax, e.g.  "Federal ",  "State", for information on receipt.
    #[serde(rename = "type")]
    #[validate(length(max = 20))]
    pub kind: String,
}

static_assertions::assert_impl_all!(TaxRateType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
