// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;

/// This contains the calculated usage of energy, charging time and idle time during a transaction.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct TotalUsageType {
    /// Total duration of the charging session (including the duration of charging and not charging), in seconds.
    pub charging_time: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub energy: Decimal,
    /// Total duration of the charging session where the EV was not charging (no energy was transferred between EVSE and EV), in seconds.
    pub idle_time: i32,
    /// Total time of reservation in seconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reservation_time: Option<i32>,
}

static_assertions::assert_impl_all!(TotalUsageType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
