// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;
use validator::Validate;

/// Cost, energy, time or SoC limit for a transaction.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct TransactionLimitType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Maximum allowed cost of transaction in currency of tariff.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_cost: Option<Decimal>,
    /// Maximum allowed energy in Wh to charge in transaction.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_energy: Option<Decimal>,
    /// Maximum State of Charge of EV in percentage.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub max_so_c: Option<u8>,
    /// Maximum duration of transaction in seconds from start to end.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_time: Option<i32>,
}

static_assertions::assert_impl_all!(TransactionLimitType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
