// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;
use validator::Validate;

/// Charging parameters for ISO 15118-20, also supporting V2X charging/discharging.+
/// All values are greater or equal to zero, with the exception of EVMinEnergyRequest, EVMaxEnergyRequest, EVTargetEnergyRequest, EVMinV2XEnergyRequest and EVMaxV2XEnergyRequest.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct V2XChargingParametersType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Energy to maximum state of charge in Wh
    /// Relates to:
    /// *ISO 15118-20*: Dynamic/Scheduled_SEReqControlModeType: EVMaximumEnergyRequest
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_max_energy_request: Option<Decimal>,
    /// Energy (in Wh) to maximum state of charge for cycling (V2X) activity.
    /// Negative value indicates that current state of charge is above V2X range.
    /// Relates to:
    /// *ISO 15118-20*: Dynamic_SEReqControlModeType: EVMaximumV2XEnergyRequest
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_max_v2_x_energy_request: Option<Decimal>,
    /// Energy to minimum allowed state of charge in Wh
    /// Relates to:
    /// *ISO 15118-20*: Dynamic/Scheduled_SEReqControlModeType: EVMinimumEnergyRequest
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_min_energy_request: Option<Decimal>,
    /// Energy (in Wh) to minimum state of charge for cycling (V2X) activity.
    /// Positive value means that current state of charge is below V2X range.
    /// Relates to:
    /// *ISO 15118-20*: Dynamic_SEReqControlModeType: EVMinimumV2XEnergyRequest
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_min_v2_x_energy_request: Option<Decimal>,
    /// Energy to requested state of charge in Wh
    /// Relates to:
    /// *ISO 15118-20*: Dynamic/Scheduled_SEReqControlModeType: EVTargetEnergyRequest
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub ev_target_energy_request: Option<Decimal>,
    /// Maximum charge current in A, defined by min(EV, EVSE)
    /// Relates to:
    /// *ISO 15118-20*: BPT_DC_CPDReqEnergyTransferModeType: EVMaximumChargeCurrent
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_current: Option<Decimal>,
    /// Maximum charge (absorbed) power in W, defined by min(EV, EVSE) at unity power factor. +
    /// This field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    /// It corresponds to the ChaWMax attribute in the IEC 61850.
    /// It is usually equivalent to the rated apparent power of the EV when discharging (ChaVAMax) in IEC 61850. +
    ///
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMaximumChargePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_power: Option<Decimal>,
    /// Maximum charge power on phase L2 in W, defined by min(EV, EVSE)
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMaximumChargePower_L2
    #[serde(rename = "maxChargePower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_power_l2: Option<Decimal>,
    /// Maximum charge power on phase L3 in W, defined by min(EV, EVSE)
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMaximumChargePower_L3
    #[serde(rename = "maxChargePower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_charge_power_l3: Option<Decimal>,
    /// Maximum discharge current in A, defined by min(EV, EVSE).  Value &gt;= 0.
    /// Relates to:
    /// *ISO 15118-20*: BPT_DC_CPDReqEnergyTransferModeType: EVMaximumDischargeCurrent
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_current: Option<Decimal>,
    /// Maximum discharge (injected) power in W, defined by min(EV, EVSE) at unity power factor.  Value &gt;= 0.
    /// This field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMaximumDischargePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_power: Option<Decimal>,
    /// Maximum discharge power on phase L2 in W, defined by min(EV, EVSE).  Value &gt;= 0.
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMaximumDischargePowe_L2
    #[serde(rename = "maxDischargePower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_power_l2: Option<Decimal>,
    /// Maximum discharge power on phase L3 in W, defined by min(EV, EVSE).  Value &gt;= 0.
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMaximumDischargePower_L3
    #[serde(rename = "maxDischargePower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_discharge_power_l3: Option<Decimal>,
    /// Maximum voltage in V, defined by min(EV, EVSE)
    /// Relates to:
    /// *ISO 15118-20*: BPT_DC_CPDReqEnergyTransferModeType: EVMaximumVoltage
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub max_voltage: Option<Decimal>,
    /// Minimum charge current in A, defined by max(EV, EVSE)
    /// Relates to:
    /// *ISO 15118-20*: BPT_DC_CPDReqEnergyTransferModeType: EVMinimumChargeCurrent
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charge_current: Option<Decimal>,
    /// Minimum charge power in W, defined by max(EV, EVSE).
    /// This field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1.
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMinimumChargePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charge_power: Option<Decimal>,
    /// Minimum charge power on phase L2 in W, defined by max(EV, EVSE).
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMinimumChargePower_L2
    #[serde(rename = "minChargePower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charge_power_l2: Option<Decimal>,
    /// Minimum charge power on phase L3 in W, defined by max(EV, EVSE).
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMinimumChargePower_L3
    #[serde(rename = "minChargePower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_charge_power_l3: Option<Decimal>,
    /// Minimum discharge current in A, defined by max(EV, EVSE).  Value &gt;= 0.
    /// Relates to:
    /// *ISO 15118-20*: BPT_DC_CPDReqEnergyTransferModeType: EVMinimumDischargeCurrent
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_discharge_current: Option<Decimal>,
    /// Minimum discharge (injected) power in W, defined by max(EV, EVSE) at unity power factor. Value &gt;= 0. +
    /// This field represents the sum of all phases, unless values are provided for L2 and L3, in which case this field represents phase L1. +
    /// It corresponds to the WMax attribute in the IEC 61850.
    /// It is usually equivalent to the rated apparent power of the EV when discharging (VAMax attribute in the IEC 61850).
    ///
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMinimumDischargePower
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_discharge_power: Option<Decimal>,
    /// Minimum discharge power on phase L2 in W, defined by max(EV, EVSE).  Value &gt;= 0.
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMinimumDischargePower_L2
    #[serde(rename = "minDischargePower_L2")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_discharge_power_l2: Option<Decimal>,
    /// Minimum discharge power on phase L3 in W, defined by max(EV, EVSE).  Value &gt;= 0.
    /// Relates to:
    /// *ISO 15118-20*: BPT_AC/DC_CPDReqEnergyTransferModeType: EVMinimumDischargePower_L3
    #[serde(rename = "minDischargePower_L3")]
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_discharge_power_l3: Option<Decimal>,
    /// Minimum voltage in V, defined by max(EV, EVSE)
    /// Relates to:
    /// *ISO 15118-20*: BPT_DC_CPDReqEnergyTransferModeType: EVMinimumVoltage
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub min_voltage: Option<Decimal>,
    /// Target state of charge at departure as percentage.
    /// Relates to:
    /// *ISO 15118-20*: BPT_DC_CPDReqEnergyTransferModeType: TargetSOC
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(range(min = 0, max = 100))]
    pub target_so_c: Option<u8>,
}

static_assertions::assert_impl_all!(V2XChargingParametersType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
