// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use rust_decimal::Decimal;

/// *(2.1)* A point of a signal-watt curve.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct V2XSignalWattPointType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Power in W to charge (positive) or discharge (negative) at specified frequency.
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    pub power: Decimal,
    /// Signal value from an AFRRSignalRequest.
    pub signal: i32,
}

static_assertions::assert_impl_all!(V2XSignalWattPointType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
