// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::power_during_cessation::PowerDuringCessationEnumType;
use rust_decimal::Decimal;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct VoltageParamsType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// Time for which the voltage is allowed to stay above the 10 min mean value.
    ///     After this time, the EV must trip.
    ///     This value is mandatory if OverVoltageMeanValue10min is set.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub hv10_min_mean_trip_delay: Option<Decimal>,
    /// EN 50549-1 chapter 4.9.3.4
    ///     Voltage threshold for the 10 min time window mean value monitoring.
    ///     The 10 min mean is recalculated up to every 3 s.
    ///     If the present voltage is above this threshold for more than the time defined by _hv10MinMeanValue_, the EV must trip.
    ///     This value is mandatory if _hv10MinMeanTripDelay_ is set.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::arbitrary_precision_option"
    )]
    pub hv10_min_mean_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub power_during_cessation: Option<PowerDuringCessationEnumType>,
}

static_assertions::assert_impl_all!(VoltageParamsType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
