// @generated by codegen — do not edit by hand.

use crate::v2_1::datatypes::custom_data::CustomDataType;
use crate::v2_1::enumerations::vpn::VPNEnumType;
use validator::Validate;

/// VPN Configuration settings
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Validate, Default)]
#[serde(rename_all = "camelCase")]
pub struct VPNType {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<CustomDataType>,
    /// VPN group.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(length(max = 50))]
    pub group: Option<String>,
    /// VPN shared secret.
    #[validate(length(max = 255))]
    pub key: String,
    /// *(2.1)* VPN Password.
    #[validate(length(max = 64))]
    pub password: String,
    /// VPN Server Address
    #[validate(length(max = 2000))]
    pub server: String,
    #[serde(rename = "type")]
    pub kind: VPNEnumType,
    /// VPN User
    #[validate(length(max = 50))]
    pub user: String,
}

static_assertions::assert_impl_all!(VPNType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default, validator::Validate);
