// @generated by codegen — do not edit by hand.

/// Battery in/out
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum BatterySwapEventEnumType {
    #[default]
    BatteryIn,
    BatteryOut,
    BatteryOutTimeout,
}

static_assertions::assert_impl_all!(BatterySwapEventEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
