// @generated by codegen — do not edit by hand.

/// Status of certificate: good, revoked or unknown.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum CertificateStatusEnumType {
    #[default]
    Good,
    Revoked,
    Unknown,
    Failed,
}

static_assertions::assert_impl_all!(CertificateStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
