// @generated by codegen — do not edit by hand.

/// Source of status: OCSP, CRL
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum CertificateStatusSourceEnumType {
    #[default]
    CRL,
    OCSP,
}

static_assertions::assert_impl_all!(CertificateStatusSourceEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
