// @generated by codegen — do not edit by hand.

/// Specifies to purpose of the charging profiles that will be cleared, if they meet the other criteria in the request.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ChargingProfilePurposeEnumType {
    #[default]
    ChargingStationExternalConstraints,
    ChargingStationMaxProfile,
    TxDefaultProfile,
    TxProfile,
    PriorityCharging,
    LocalGeneration,
}

static_assertions::assert_impl_all!(ChargingProfilePurposeEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
