// @generated by codegen — do not edit by hand.

/// Indicates the kind of schedule.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ChargingProfileKindEnumType {
    #[default]
    Absolute,
    Recurring,
    Relative,
    Dynamic,
}

static_assertions::assert_impl_all!(ChargingProfileKindEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
