// @generated by codegen — do not edit by hand.

/// Current charging state, is required when state
/// has changed. Omitted when there is no communication between EVSE and EV, because no cable is plugged in.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ChargingStateEnumType {
    #[default]
    EVConnected,
    Charging,
    SuspendedEV,
    SuspendedEVSE,
    Idle,
}

static_assertions::assert_impl_all!(ChargingStateEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
