// @generated by codegen — do not edit by hand.

/// Returns whether the Charging Station has been able to remove the message.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ClearMessageStatusEnumType {
    #[default]
    Accepted,
    Unknown,
    Rejected,
}

static_assertions::assert_impl_all!(ClearMessageStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
