// @generated by codegen — do not edit by hand.

/// *(2.1)* Indicates whether EV wants to operate in Dynamic or Scheduled mode. When absent, Scheduled mode is assumed for backwards compatibility. +
/// *ISO 15118-20:* +
/// ServiceSelectionReq(SelectedEnergyTransferService)
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ControlModeEnumType {
    #[default]
    ScheduledControl,
    DynamicControl,
}

static_assertions::assert_impl_all!(ControlModeEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
