// @generated by codegen — do not edit by hand.

/// The kind of cost referred to in the message element amount
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum CostKindEnumType {
    #[default]
    CarbonDioxideEmission,
    RelativePricePercentage,
    RenewableGenerationPercentage,
}

static_assertions::assert_impl_all!(CostKindEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
