// @generated by codegen — do not edit by hand.

/// Type of cost dimension: energy, power, time, etc.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum CostDimensionEnumType {
    #[default]
    Energy,
    MaxCurrent,
    MinCurrent,
    MaxPower,
    MinPower,
    IdleTIme,
    ChargingTime,
}

static_assertions::assert_impl_all!(CostDimensionEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
