// @generated by codegen — do not edit by hand.

/// Result of operation.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum DERControlStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    NotSupported,
    NotFound,
}

static_assertions::assert_impl_all!(DERControlStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
