// @generated by codegen — do not edit by hand.

/// Unit of the Y-axis of DER curve
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum DERUnitEnumType {
    #[default]
    #[serde(rename = "Not_Applicable")]
    NotApplicable,
    PctMaxW,
    PctMaxVar,
    PctWAvail,
    PctVarAvail,
    PctEffectiveV,
}

static_assertions::assert_impl_all!(DERUnitEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
