// @generated by codegen — do not edit by hand.

/// Mode of energy transfer requested by the EV.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum EnergyTransferModeEnumType {
    #[default]
    #[serde(rename = "AC_single_phase")]
    ACSinglePhase,
    #[serde(rename = "AC_two_phase")]
    ACTwoPhase,
    #[serde(rename = "AC_three_phase")]
    ACThreePhase,
    DC,
    #[serde(rename = "AC_BPT")]
    ACBPT,
    #[serde(rename = "AC_BPT_DER")]
    ACBPTDER,
    #[serde(rename = "AC_DER")]
    ACDER,
    #[serde(rename = "DC_BPT")]
    DCBPT,
    #[serde(rename = "DC_ACDP")]
    DCACDP,
    #[serde(rename = "DC_ACDP_BPT")]
    DCACDPBPT,
    WPT,
}

static_assertions::assert_impl_all!(EnergyTransferModeEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
