// @generated by codegen — do not edit by hand.

/// Type of trigger for this event, e.g. exceeding a threshold value.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum EventTriggerEnumType {
    #[default]
    Alerting,
    Delta,
    Periodic,
}

static_assertions::assert_impl_all!(EventTriggerEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
