// @generated by codegen — do not edit by hand.

/// Type of EVSE (AC, DC) this tariff applies to.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum EvseKindEnumType {
    #[default]
    AC,
    DC,
}

static_assertions::assert_impl_all!(EvseKindEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
