// @generated by codegen — do not edit by hand.

/// Indicates the type of the requested certificate(s).
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum GetCertificateIdUseEnumType {
    #[default]
    V2GRootCertificate,
    MORootCertificate,
    CSMSRootCertificate,
    V2GCertificateChain,
    ManufacturerRootCertificate,
    OEMRootCertificate,
}

static_assertions::assert_impl_all!(GetCertificateIdUseEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
