// @generated by codegen — do not edit by hand.

/// Indicates where the measured value has been sampled. Default =  "Outlet"
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum LocationEnumType {
    Body,
    Cable,
    EV,
    Inlet,
    #[default]
    Outlet,
    Upstream,
}

static_assertions::assert_impl_all!(LocationEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
