// @generated by codegen — do not edit by hand.

/// If provided the Charging Station shall return Display Messages with the given priority only.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum MessagePriorityEnumType {
    #[default]
    AlwaysFront,
    InFront,
    NormalCycle,
}

static_assertions::assert_impl_all!(MessagePriorityEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
