// @generated by codegen — do not edit by hand.

/// Format of the message.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum MessageFormatEnumType {
    #[default]
    ASCII,
    HTML,
    URI,
    UTF8,
    QRCODE,
}

static_assertions::assert_impl_all!(MessageFormatEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
