// @generated by codegen — do not edit by hand.

/// During what state should this message be shown. When omitted this message should be shown in any state of the Charging Station.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum MessageStateEnumType {
    #[default]
    Charging,
    Faulted,
    Idle,
    Unavailable,
    Suspended,
    Discharging,
}

static_assertions::assert_impl_all!(MessageStateEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
