// @generated by codegen — do not edit by hand.

/// *(2.1)* Value of EVCC indicates that EV determines min/target SOC and departure time. +
/// A value of EVCC_SECC indicates that charging station or CSMS may also update min/target SOC and departure time. +
/// *ISO 15118-20:* +
/// ServiceSelectionReq(SelectedEnergyTransferService)
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum MobilityNeedsModeEnumType {
    #[default]
    EVCC,
    #[serde(rename = "EVCC_SECC")]
    EVCCSECC,
}

static_assertions::assert_impl_all!(MobilityNeedsModeEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
