// @generated by codegen — do not edit by hand.

/// The type of this monitor, e.g. a threshold, delta or periodic monitor.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum MonitorEnumType {
    #[default]
    UpperThreshold,
    LowerThreshold,
    Delta,
    Periodic,
    PeriodicClockAligned,
    TargetDelta,
    TargetDeltaRelative,
}

static_assertions::assert_impl_all!(MonitorEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
