// @generated by codegen — do not edit by hand.

/// Returns whether the CSMS has been able to process the message successfully. It does not imply that the evChargingNeeds can be met with the current charging profile.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum NotifyEVChargingNeedsStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    Processing,
    NoChargingProfile,
}

static_assertions::assert_impl_all!(NotifyEVChargingNeedsStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
