// @generated by codegen — do not edit by hand.

/// Defines the transport protocol (e.g. SOAP or JSON). Note: SOAP is not supported in OCPP 2.x, but is supported by earlier versions of OCPP.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum OCPPTransportEnumType {
    #[default]
    SOAP,
    JSON,
}

static_assertions::assert_impl_all!(OCPPTransportEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
