// @generated by codegen — do not edit by hand.

/// *(2.1)* Charging operation mode to use during this time interval. When absent defaults to `ChargingOnly`.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum OperationModeEnumType {
    #[default]
    Idle,
    ChargingOnly,
    CentralSetpoint,
    ExternalSetpoint,
    ExternalLimits,
    CentralFrequency,
    LocalFrequency,
    LocalLoadBalancing,
}

static_assertions::assert_impl_all!(OperationModeEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
