// @generated by codegen — do not edit by hand.

/// Parameter is only sent, if the EV has to feed-in power or reactive power during fault-ride through (FRT) as defined by HVMomCess curve and LVMomCess curve.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum PowerDuringCessationEnumType {
    #[default]
    Active,
    Reactive,
}

static_assertions::assert_impl_all!(PowerDuringCessationEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
