// @generated by codegen — do not edit by hand.

/// *(2.1)* The current preconditioning status of the BMS in the EV. Default value is Unknown.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum PreconditioningStatusEnumType {
    #[default]
    Unknown,
    Ready,
    NotReady,
    Preconditioning,
}

static_assertions::assert_impl_all!(PreconditioningStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
