// @generated by codegen — do not edit by hand.

/// Result of the request.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum PriorityChargingStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    NoProfile,
}

static_assertions::assert_impl_all!(PriorityChargingStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
