// @generated by codegen — do not edit by hand.

/// Indicates the start point of a recurrence.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum RecurrencyKindEnumType {
    #[default]
    Daily,
    Weekly,
}

static_assertions::assert_impl_all!(RecurrencyKindEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
