// @generated by codegen — do not edit by hand.

/// This contains the type of reset that the Charging Station or EVSE should perform.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ResetEnumType {
    #[default]
    Immediate,
    OnIdle,
    ImmediateAndResume,
}

static_assertions::assert_impl_all!(ResetEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
