// @generated by codegen — do not edit by hand.

/// The updated reservation status.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum ReservationUpdateStatusEnumType {
    #[default]
    Expired,
    Removed,
    NoTransaction,
}

static_assertions::assert_impl_all!(ReservationUpdateStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
