// @generated by codegen — do not edit by hand.

/// Status of the operation
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum TariffChangeStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    TooManyElements,
    ConditionNotSupported,
    TxNotFound,
    NoCurrencyChange,
}

static_assertions::assert_impl_all!(TariffChangeStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
