// @generated by codegen — do not edit by hand.

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum TariffClearStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    NoTariff,
}

static_assertions::assert_impl_all!(TariffClearStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
