// @generated by codegen — do not edit by hand.

/// Status of operation
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum TariffGetStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    NoTariff,
}

static_assertions::assert_impl_all!(TariffGetStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
