// @generated by codegen — do not edit by hand.

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum TariffSetStatusEnumType {
    #[default]
    Accepted,
    Rejected,
    TooManyElements,
    ConditionNotSupported,
    DuplicateTariffId,
}

static_assertions::assert_impl_all!(TariffSetStatusEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
