// @generated by codegen — do not edit by hand.

/// Type of cost: normal or the minimum or maximum cost.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum TariffCostEnumType {
    #[default]
    NormalCost,
    MinCost,
    MaxCost,
}

static_assertions::assert_impl_all!(TariffCostEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
