// @generated by codegen — do not edit by hand.

/// Type of VPN
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub enum VPNEnumType {
    #[default]
    IKEv2,
    IPSec,
    L2TP,
    PPTP,
}

static_assertions::assert_impl_all!(VPNEnumType: serde::Serialize, serde::de::DeserializeOwned, Clone, core::fmt::Debug, PartialEq, Default);
